export interface CalculatorItem {
  id: string;
  title: string;
  category: "Cardiovascular & Vitals" | "Metabolic & Lab" | "Body Composition & Hydration" | "Financial & Pricing";
  iconName: "Activity" | "HeartPulse" | "Calculator" | "Users" | "Droplet" | "DollarSign" | "Smile";
  desc: string;
  href: string;
  badge?: string;
  features: string[];
  image: string;
  stat: string;
  statLabel: string;
}

export const calculatorData: CalculatorItem[] = [
  {
    id: "a1c-calculator",
    title: "A1C Calculator",
    category: "Metabolic & Lab",
    iconName: "Calculator",
    desc: "Estimate average blood glucose level (eAG) from A1C percentage or calculate A1C from eAG using standard clinical formulas.",
    href: "/calculators/a1c-calculator",
    badge: "Clinical Standard",
    features: ["A1C to eAG conversion", "eAG to A1C conversion", "ADA aligned glycemic targets"],
    image: "/llm_healthcare_hero.png",
    stat: "eAG",
    statLabel: "Glycemic Index Estimator",
  },
  {
    id: "water-intake-calculator",
    title: "Water Intake Calculator",
    category: "Body Composition & Hydration",
    iconName: "Droplet",
    desc: "Calculate your personalized daily hydration requirement based on weight, daily activity level, exercise duration, and climate offsets.",
    href: "/calculators/water-intake-calculator",
    badge: "Hydration Guide",
    features: ["35 mL/kg baseline index", "Exercise and climate offsets", "Hydration entry logging companion"],
    image: "/blog_predictive_scheduling.png",
    stat: "Hydration",
    statLabel: "Daily Fluid Target",
  },
  {
    id: "lean-body-mass-calculator",
    title: "Lean Body Mass Calculator",
    category: "Body Composition & Hydration",
    iconName: "Users",
    desc: "Estimate your lean body mass and body fat percentage utilizing Boer, James, or Hume clinical equations.",
    href: "/calculators/lean-body-mass-calculator",
    badge: "Body Composition",
    features: ["Boer, James, and Hume formulas", "Metric and Imperial support", "Lean mass percentage tracking"],
    image: "/hw_patient_journey.png",
    stat: "LBM %",
    statLabel: "Lean Mass Percentage",
  },
  {
    id: "metabolic-age-calculator",
    title: "Metabolic Age Calculator",
    category: "Body Composition & Hydration",
    iconName: "Activity",
    desc: "Estimate your body's metabolic age and health level based on body composition, activity, and daily lifestyle habits.",
    href: "/calculators/metabolic-age-calculator",
    badge: "Metabolic Health",
    features: ["Mifflin-St Jeor and Katch-McArdle", "Lifestyle and sleep offsets", "Interactive progress and logs tracking"],
    image: "/llm_healthcare_hero.png",
    stat: "Metabolic Age",
    statLabel: "Biological Health Index",
  },
  {
    id: "baby-weight-calculator",
    title: "Baby Weight Calculator",
    category: "Body Composition & Hydration",
    iconName: "Users",
    desc: "Estimate expected baby weight and growth percentiles based on World Health Organization infant growth standards.",
    href: "/calculators/baby-weight-calculator",
    badge: "Pediatric Care",
    features: ["WHO Growth Standards index", "Boys and Girls percentiles", "Interactive weight growth logbook"],
    image: "/hw_patient_journey.png",
    stat: "Percentiles",
    statLabel: "WHO Growth Percentile",
  },
  {
    id: "baby-age-calculator",
    title: "Baby Age Calculator",
    category: "Body Composition & Hydration",
    iconName: "Calculator",
    desc: "Calculate your baby's exact age in weeks, months, and days. Track growth milestones and developmental stages easily.",
    href: "/calculators/baby-age-calculator",
    badge: "Development Stages",
    features: ["Years, Months, Days breakdown", "Prematurity corrected ages", "CDC Milestones checklists tracker"],
    image: "/llm_healthcare_hero.png",
    stat: "Milestones",
    statLabel: "CDC Development Index",
  },
  {
    id: "glasgow-coma-scale-calculator",
    title: "Glasgow Coma Scale Calculator",
    category: "Cardiovascular & Vitals",
    iconName: "HeartPulse",
    desc: "Use our free Glasgow Coma Scale Calculator to calculate GCS score based on eye, verbal, and motor responses.",
    href: "/calculators/glasgow-coma-scale-calculator",
    badge: "Neurology",
    features: ["Eye, Verbal, and Motor parameters", "Intubated Patient toggle (V1T)", "Severity levels categorization"],
    image: "/llm_healthcare_hero.png",
    stat: "GCS",
    statLabel: "Consciousness Score",
  },
  {
    id: "qtc-calculator",
    title: "QTc Calculator (Bazett, Fridericia & More)",
    category: "Cardiovascular & Vitals",
    iconName: "HeartPulse",
    desc: "Calculate the corrected QT interval (QTc) from ECG metrics using Bazett, Fridericia, Framingham, and Hodges clinical formulas.",
    href: "/calculators/qtc-calculator",
    badge: "Cardiology",
    features: ["Bazett/Fridericia/Framingham/Hodges", "Arrhythmia risk screening", "ECG QT interval indexer"],
    image: "/service_telemedicine.png",
    stat: "QTc",
    statLabel: "Corrected QT Interval",
  },
  {
    id: "anion-gap-calculator",
    title: "Anion Gap Calculator",
    category: "Metabolic & Lab",
    iconName: "Activity",
    desc: "Calculate serum anion gap to assist clinicians in screening for potential metabolic acidosis and underlying causes.",
    href: "/calculators/anion-gap-calculator",
    badge: "Lab Reference",
    features: ["Serum anion gap index", "Hypoalbuminemia adjustments", "Metabolic acidosis screening"],
    image: "/blog_hipaa_datastore.png",
    stat: "Serum AG",
    statLabel: "Anion Gap Index",
  },
  {
    id: "dental-implant-cost-calculator",
    title: "Dental Implant Cost Calculator",
    category: "Financial & Pricing",
    iconName: "DollarSign",
    desc: "Estimate total orthodontic implant procedures expenses based on regional cost indexing, restoration types, and bone grafting options.",
    href: "/calculators/dental-implant-cost-calculator",
    badge: "Treatment Pricing",
    features: ["Location-based cost adjustments", "Single crown to All-on-6 setups", "Bone grafting and extraction options"],
    image: "/service_patient_portal.png",
    stat: "Cost Est.",
    statLabel: "Orthodontic Cost Estimator",
  },
  {
    id: "invisalign-cost-calculator",
    title: "Invisalign Cost Calculator",
    category: "Financial & Pricing",
    iconName: "DollarSign",
    desc: "Estimate the potential cost of Invisalign treatment based on treatment complexity, duration, and dental needs.",
    href: "/calculators/invisalign-cost-calculator",
    badge: "Treatment Pricing",
    features: ["Complexity and duration offsets", "Insurance and HSA/FSA reductions", "Monthly financing estimator"],
    image: "/service_patient_portal.png",
    stat: "Invisalign Est.",
    statLabel: "Clear Aligner Estimator",
  },
  {
    id: "insulin-dosage-calculator",
    title: "Insulin Dosage Calculator",
    category: "Metabolic & Lab",
    iconName: "Calculator",
    desc: "Calculate rapid-acting bolus insulin dosage based on carbohydrate intake and current blood glucose levels, or estimate starting parameters.",
    href: "/calculators/insulin-dosage-calculator",
    badge: "Clinical Tool",
    features: ["Bolus dose calculations", "Rule of 1800/100 sensitivity estimation", "Rule of 500 carb ratio estimation"],
    image: "/llm_healthcare_hero.png",
    stat: "Bolus Dose",
    statLabel: "Insulin Dose Estimator",
  },
  {
    id: "ckd-calculator",
    title: "CKD Calculator (eGFR)",
    category: "Metabolic & Lab",
    iconName: "Calculator",
    desc: "Calculate estimated Glomerular Filtration Rate (eGFR) and staging using modern CKD-EPI 2021 or traditional MDRD equations.",
    href: "/calculators/ckd-calculator",
    badge: "Renal Function",
    features: ["CKD-EPI 2021 race-free equation", "MDRD IDMS-traceable equation", "eGFR color-coded staging analysis"],
    image: "/llm_healthcare_hero.png",
    stat: "eGFR",
    statLabel: "Renal Clearance Estimator",
  },
  {
    id: "iv-drip-rate-calculator",
    title: "IV Drip Rate Calculator",
    category: "Cardiovascular & Vitals",
    iconName: "HeartPulse",
    desc: "Calculate IV flow rate in mL/hour, drops per minute (gtt/min), and infusion duration using macrodrip or microdrip configurations.",
    href: "/calculators/iv-drip-rate-calculator",
    badge: "Infusion Guide",
    features: ["Flow Rate in mL/hour", "Drops per Minute (gtt/min)", "microdrip & macrodrip sets calibration"],
    image: "/llm_healthcare_hero.png",
    stat: "gtt/min",
    statLabel: "IV Flow Rate Estimator",
  },
  {
    id: "cpt-calculator",
    title: "CPT Calculator",
    category: "Financial & Pricing",
    iconName: "DollarSign",
    desc: "Understand CPT procedure codes and billing estimates using Work, Practice Expense, and Malpractice RVUs.",
    href: "/calculators/cpt-calculator",
    badge: "Medical Coding",
    features: ["Predefined E/M CPT codes database", "Geographic GPCI indexing offsets", "Patient co-insurance and modifiers"],
    image: "/service_patient_portal.png",
    stat: "Total Fee",
    statLabel: "Procedure Billing Estimator",
  },
  {
    id: "fat-intake-calculator",
    title: "Fat Intake Calculator",
    category: "Body Composition & Hydration",
    iconName: "Activity",
    desc: "Calculate your recommended daily dietary fat intake and healthy fat needs based on calorie budget, goals, and lifestyle.",
    href: "/calculators/fat-intake-calculator",
    badge: "Dietary Guide",
    features: ["Direct Calorie target entry", "TDEE calorie needs estimator", "Daily fat breakdown (Unsaturated, Saturated, Trans)"],
    image: "/llm_healthcare_hero.png",
    stat: "Fat Intake",
    statLabel: "Daily Fat Target Estimator",
  },
  {
    id: "medication-dosage-calculator",
    title: "Medication Dosage Calculator",
    category: "Metabolic & Lab",
    iconName: "Calculator",
    desc: "Calculate medication dosage target volumes or tablet counts using standard clinical equations and weight metrics.",
    href: "/calculators/medication-dosage-calculator",
    badge: "Dosage Math",
    features: ["Standard & Weight-Based dosing modes", "Metric and Imperial weight toggles", "Interactive dosage logs indexer"],
    image: "/llm_healthcare_hero.png",
    stat: "Dose Qty",
    statLabel: "Administration Volume Estimator",
  },
  {
    id: "hba1c-calculator",
    title: "HbA1c Calculator",
    category: "Metabolic & Lab",
    iconName: "Calculator",
    desc: "Convert HbA1c percentage to estimated average glucose (eAG) and categorize blood sugar control ranges.",
    href: "/calculators/hba1c-calculator",
    badge: "Glycemic Index",
    features: ["A1C to eAG conversion", "Reverse eAG to A1C conversion", "ADA aligned glycemic targets"],
    image: "/llm_healthcare_hero.png",
    stat: "eAG Target",
    statLabel: "Glycemic Range Estimator",
  },
  {
    id: "pediatric-dosage-calculator",
    title: "Pediatric Dosage Calculator",
    category: "Metabolic & Lab",
    iconName: "Calculator",
    desc: "Calculate safe pediatric medication doses based on body weight, concentration, and prescribed frequency rates.",
    href: "/calculators/pediatric-dosage-calculator",
    badge: "Pediatric Care",
    features: ["Weight-based dosing math", "Liquid volume conversion", "Predefined frequency intervals"],
    image: "/llm_healthcare_hero.png",
    stat: "Single Dose",
    statLabel: "Pediatric Dose Estimator",
  },
  {
    id: "fetal-growth-calculator",
    title: "Fetal Growth Calculator",
    category: "Body Composition & Hydration",
    iconName: "Calculator",
    desc: "Estimate fetal size by week of pregnancy and calculate estimated fetal weight (EFW) using ultrasound biometrics.",
    href: "/calculators/fetal-growth-calculator",
    badge: "Pregnancy Care",
    features: ["Week-by-week growth tracker", "Hadlock ultrasound biometrics", "Saved growth metrics logs"],
    image: "/llm_healthcare_hero.png",
    stat: "EFW (g)",
    statLabel: "Fetal Growth Estimator",
  },
  {
    id: "iv-flow-rate-calculator",
    title: "IV Flow Rate Calculator",
    category: "Cardiovascular & Vitals",
    iconName: "Activity",
    desc: "Calculate IV infusion flow rate in mL/hour, drops per minute (gtt/min), and total duration to ensure accurate fluid and medication administration.",
    href: "/calculators/iv-flow-rate-calculator",
    badge: "Clinical Math",
    features: [
      "mL/hour infusion speed",
      "Drops per minute (gtt/min) rate",
      "Linear growth learning widget"
    ],
    image: "/llm_healthcare_hero.png",
    stat: "mL/hr & gtt",
    statLabel: "Infusion Speed Estimator",
  },
  {
    id: "baby-growth-calculator",
    title: "Baby Growth Calculator",
    category: "Body Composition & Hydration",
    iconName: "Calculator",
    desc: "Track your baby’s growth, height, weight, and developmental milestones to understand healthy child growth patterns easily.",
    href: "/calculators/baby-growth-calculator",
    badge: "Pediatric Care",
    features: [
      "WHO Percentiles Lookups",
      "Dynamic Growth Curves Plotter",
      "Age-Based Milestones Guide"
    ],
    image: "/llm_healthcare_hero.png",
    stat: "WHO Percentiles",
    statLabel: "Growth Status Tracker",
  },
  {
    id: "infusion-calculator",
    title: "Infusion Calculator",
    category: "Cardiovascular & Vitals",
    iconName: "Activity",
    desc: "Calculate IV infusion rate, flow speed, and drip rate (gtt/min) for both standard fluids and patient weight-based drug doses.",
    href: "/calculators/infusion-calculator",
    badge: "Clinical Dosing",
    features: [
      "Standard fluid flow rate",
      "Patient weight-based dosing",
      "mL/hr & gtt/min calculations"
    ],
    image: "/llm_healthcare_hero.png",
    stat: "mL/hr & gtt",
    statLabel: "Infusion Speed Estimator",
  },
  {
    id: "stress-calculator",
    title: "Stress Calculator",
    category: "Body Composition & Hydration",
    iconName: "Smile",
    desc: "Estimate your stress level based on lifestyle, workload, emotional factors, physical activity, daily pressure, and social support.",
    href: "/calculators/stress-calculator",
    badge: "Mental Wellbeing",
    features: [
      "Dynamic stress vectors loading",
      "Personalized wellness recommendations",
      "4-7-8 breathing pacer widget"
    ],
    image: "/llm_healthcare_hero.png",
    stat: "Wellbeing Score",
    statLabel: "Stress Level Estimator",
  }
];
