"use client";
import { useState } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowRight, Sparkles, FileText, Shield, Activity, Upload, CheckCircle, Globe, Database, Layers, Send, Code, AlertCircle, Server, Users, MessageSquare } from "lucide-react";

interface TechSkill { name: string; level: string; color: string; }
interface TechArea { title: string; desc: string; icon: React.ReactNode; }

export default function JobClient() {
  const [activeTab, setActiveTab] = useState<'description'|'apply'>('description');
  const [formStep, setFormStep] = useState(1);
  const [formData, setFormData] = useState({ name:'',email:'',portfolioUrl:'',primaryLang:'customer_success_eng',expYears:'3-5',cloudExp:'yes',resumeFile:null as File|null,resumeName:'' });
  const [sandboxSetup, setSandboxSetup] = useState({ supportTriage:'',integrationTroubleshoot:'',adoptionChrn:'' });
  const [sandboxAttempts, setSandboxAttempts] = useState(0);
  const [sandboxSuccess, setSandboxSuccess] = useState(false);
  const [sandboxError, setSandboxError] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitSuccess, setSubmitSuccess] = useState(false);

  const technicalSkills: TechSkill[] = [
    { name:'SaaS Customer Success', level:'Required', color:'text-brand-cyan bg-brand-cyan/10 border-brand-cyan/20' },
    { name:'EHR/EMR Integrations', level:'Required', color:'text-brand-indigo bg-brand-indigo/10 border-brand-indigo/20' },
    { name:'API Troubleshooting', level:'Required', color:'text-brand-emerald bg-brand-emerald/10 border-brand-emerald/20' },
    { name:'SQL & Data Queries', level:'Required', color:'text-purple-400 bg-purple-400/10 border-purple-400/20' },
    { name:'HIPAA & Compliance', level:'Required', color:'text-amber-400 bg-amber-400/10 border-amber-400/20' },
    { name:'Technical Account Mgmt', level:'Preferred', color:'text-rose-400 bg-rose-400/10 border-rose-400/20' },
  ];

  const techAreas: TechArea[] = [
    { title:'Healthcare SaaS Platforms', desc:'Support secure multi-tenant user portals and role-based access management settings.', icon:<Layers className="w-5 h-5" /> },
    { title:'Patient Portal Systems', desc:'Assist clients in configuring patient self-service portals, registration, and forms workflows.', icon:<Users className="w-5 h-5" /> },
    { title:'EHR/EMR Integrations', desc:'Troubleshoot FHIR/HL7 connectivity issues and data synchronization pathways with Epic and Cerner.', icon:<Database className="w-5 h-5" /> },
    { title:'Telemedicine Solutions', desc:'Solve real-time WebRTC audio/video streaming connection bugs and patient-doctor routing errors.', icon:<Activity className="w-5 h-5" /> },
    { title:'AI Healthcare Applications', desc:'Optimize AI medical dictation or automated workflow tools with customized clinician settings.', icon:<Sparkles className="w-5 h-5" /> },
    { title:'Automation Workflows', desc:'Configure automated clinical intake, appointment reminders, and billing report runs.', icon:<Code className="w-5 h-5" /> },
  ];

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => { if (e.target.files?.[0]) { const f=e.target.files[0]; setFormData(p=>({...p,resumeFile:f,resumeName:f.name})); } };
  const handleDragOver = (e: React.DragEvent) => { e.preventDefault(); };
  const handleDrop = (e: React.DragEvent) => { e.preventDefault(); if (e.dataTransfer.files?.[0]) { const f=e.dataTransfer.files[0]; setFormData(p=>({...p,resumeFile:f,resumeName:f.name})); } };

  const validateSandbox = () => {
    setSandboxAttempts(p=>p+1);
    const ok1=sandboxSetup.supportTriage==='triage_crit_ehr_block';
    const ok2=sandboxSetup.integrationTroubleshoot==='epic_credentials_auth';
    const ok3=sandboxSetup.adoptionChrn==='proactive_training_audit';
    if(ok1&&ok2&&ok3){setSandboxSuccess(true);setSandboxError('');}
    else{setSandboxSuccess(false);let n=0;if(!ok1)n++;if(!ok2)n++;if(!ok3)n++;setSandboxError('Customer Success pre-screen failed. '+n+'/3 decisions are non-optimal. Hint: Prioritize issues that block patient care immediately; verify OAuth credentials and IP whitelists for EHR auth errors; and investigate audit logs and offer active workflow training sessions to counter drop-offs.');}
  };

  const submitApplication = async () => { setIsSubmitting(true); await new Promise(r=>setTimeout(r,2000)); setIsSubmitting(false); setSubmitSuccess(true); };
  const resetForm = () => { setFormStep(1);setSubmitSuccess(false);setSandboxSuccess(false);setSandboxAttempts(0);setSandboxSetup({supportTriage:'',integrationTroubleshoot:'',adoptionChrn:''});setFormData({name:'',email:'',portfolioUrl:'',primaryLang:'customer_success_eng',expYears:'3-5',cloudExp:'yes',resumeFile:null,resumeName:''}); };

  return (<div className="relative overflow-hidden min-h-screen">
    <div className="fixed top-0 right-1/4 w-[600px] h-[600px] bg-brand-cyan/5 rounded-full blur-[130px] -z-10 pointer-events-none" />
    <div className="fixed bottom-0 left-1/4 w-[500px] h-[500px] bg-brand-indigo/5 rounded-full blur-[130px] -z-10 pointer-events-none" />
    <div className="max-w-6xl mx-auto px-6 py-12 md:py-16">
      <div className="mb-8 flex items-center space-x-2 text-xs"><Link href="/" className="text-gray-500 hover:text-brand-cyan transition-colors">Home</Link><span className="text-gray-600">/</span><Link href="/careers" className="text-gray-500 hover:text-brand-cyan transition-colors">Careers</Link><span className="text-gray-600">/</span><span className="text-white">Customer Success Engineer</span></div>
      <header className="mb-12 relative"><div className="absolute -inset-1 bg-gradient-to-r from-brand-cyan/20 to-brand-indigo/20 rounded-3xl blur-2xl opacity-40 -z-10 pointer-events-none" /><div className="glass-panel border border-brand-border rounded-3xl p-8 md:p-12"><div className="grid grid-cols-1 md:grid-cols-12 gap-8 items-center">
        <div className="md:col-span-8 space-y-6">
          <div className="inline-flex items-center space-x-2 bg-gradient-to-r from-brand-cyan/15 to-brand-indigo/15 border border-brand-cyan/20 rounded-full px-4 py-1.5"><div className="w-1.5 h-1.5 bg-brand-cyan rounded-full animate-pulse" /><span className="text-[10px] font-bold text-brand-cyan uppercase tracking-widest">Client Success & Integrations</span><Sparkles className="w-3 h-3 text-brand-cyan" /></div>
          <h1 className="font-display font-extrabold text-3xl sm:text-4xl lg:text-5xl text-white leading-tight">Customer Success Engineer Careers at Med Clinic X</h1>
          <p className="text-sm md:text-base text-gray-300 max-w-2xl leading-relaxed">Support healthcare clients through technical onboarding, platform adoption, troubleshooting, and ongoing success.</p>
          <div className="flex flex-wrap gap-3">
            <span className="inline-flex items-center space-x-1.5 text-xs font-semibold px-3 py-1 bg-white/5 border border-brand-border rounded-lg text-white"><Users className="w-3.5 h-3.5 text-brand-cyan" /><span>Customer Success</span></span>
            <span className="inline-flex items-center space-x-1.5 text-xs font-semibold px-3 py-1 bg-white/5 border border-brand-border rounded-lg text-white"><Globe className="w-3.5 h-3.5 text-brand-indigo" /><span>Remote (US Only)</span></span>
            
          </div>
        </div>
        <div className="md:col-span-4 flex justify-start md:justify-end"><button onClick={()=>{setActiveTab('apply');const el=document.getElementById('job-content');if(el)el.scrollIntoView({behavior:'smooth'});}} className="w-full md:w-auto inline-flex items-center justify-center space-x-2 bg-gradient-to-r from-brand-cyan to-brand-indigo text-white font-bold px-8 py-4 rounded-2xl hover:opacity-95 transition-opacity shadow-lg shadow-brand-indigo/10 text-sm cursor-pointer"><span>Apply for this Role</span><ArrowRight className="w-4 h-4" /></button></div>
      </div></div></header>
      <div className="border-b border-brand-border mb-8 flex space-x-8">
        <button onClick={()=>setActiveTab('description')} className={`pb-4 text-sm font-bold border-b-2 transition-all cursor-pointer ${activeTab==='description'?'border-brand-cyan text-brand-cyan':'border-transparent text-gray-400 hover:text-white'}`}>Job Description</button>
        <button onClick={()=>setActiveTab('apply')} className={`pb-4 text-sm font-bold border-b-2 transition-all cursor-pointer ${activeTab==='apply'?'border-brand-cyan text-brand-cyan':'border-transparent text-gray-400 hover:text-white'}`}>Apply Portal</button>
      </div>
      <div id="job-content" className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start"><AnimatePresence mode="wait">
        {activeTab==='description' ? (
          <motion.div key="description" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-15}} transition={{duration:0.3}} className="lg:col-span-8 space-y-10">
            <section className="space-y-4"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">About Med Clinic X</h2><p className="text-sm text-gray-300 leading-relaxed">Med Clinic X is a healthcare technology company building secure and innovative digital health solutions for healthcare organizations across the United States.</p><p className="text-sm text-gray-300 leading-relaxed">We develop healthcare SaaS platforms, AI-driven healthcare systems, patient portals, telemedicine solutions, automation workflows, and integrated healthcare products that help clinics, hospitals, and medical organizations improve operations and patient experiences.</p><p className="text-sm text-gray-300 leading-relaxed">Our mission is to help healthcare organizations successfully adopt and maximize the value of modern technology.</p></section>
            <section className="space-y-4"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">Job Overview</h2><p className="text-sm text-gray-300 leading-relaxed">We are seeking a <strong>Customer Success Engineer</strong> to support healthcare clients through technical onboarding, platform adoption, troubleshooting, and ongoing success.</p><p className="text-sm text-gray-300 leading-relaxed">In this role, you will combine technical expertise with customer-facing skills to ensure healthcare organizations successfully implement and use Med Clinic X solutions. You will work closely with customers, engineering teams, and product teams to solve technical challenges and improve client outcomes.</p></section>
            <section className="space-y-6"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">Responsibilities</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="glass-panel border border-brand-border p-5 rounded-2xl space-y-2"><div className="w-7 h-7 bg-brand-cyan/10 border border-brand-cyan/20 rounded-lg flex items-center justify-center text-brand-cyan mb-2"><MessageSquare className="w-4 h-4" /></div><h3 className="font-semibold text-white text-sm">Customer Technical Support</h3><ul className="text-xs text-gray-400 space-y-1.5 list-disc list-inside"><li>Act as a technical partner for healthcare customers.</li><li>Troubleshoot platform issues and provide technical guidance.</li><li>Support customer onboarding and product adoption.</li><li>Help clients achieve their technology goals.</li></ul></div>
              <div className="glass-panel border border-brand-border p-5 rounded-2xl space-y-2"><div className="w-7 h-7 bg-brand-indigo/10 border border-brand-indigo/20 rounded-lg flex items-center justify-center text-brand-indigo mb-2"><Database className="w-4 h-4" /></div><h3 className="font-semibold text-white text-sm">Healthcare SaaS Implementation</h3><ul className="text-xs text-gray-400 space-y-1.5 list-disc list-inside"><li>Assist with deployment and configuration of platforms.</li><li>Support API integrations and technical workflows.</li><li>Troubleshoot EHR/EMR connectivity issues.</li><li>Ensure smooth implementation experiences.</li></ul></div>
              <div className="glass-panel border border-brand-border p-5 rounded-2xl space-y-2"><div className="w-7 h-7 bg-brand-emerald/10 border border-brand-emerald/20 rounded-lg flex items-center justify-center text-brand-emerald mb-2"><Users className="w-4 h-4" /></div><h3 className="font-semibold text-white text-sm">Client Success & Optimization</h3><ul className="text-xs text-gray-400 space-y-1.5 list-disc list-inside"><li>Understand customer workflows and business needs.</li><li>Recommend best practices for platform usage.</li><li>Monitor customer health and identify improvements.</li><li>Collect feedback to improve products and services.</li></ul></div>
              <div className="glass-panel border border-brand-border p-5 rounded-2xl space-y-2"><div className="w-7 h-7 bg-purple-500/10 border border-purple-500/20 rounded-lg flex items-center justify-center text-purple-400 mb-2"><Code className="w-4 h-4" /></div><h3 className="font-semibold text-white text-sm">Engineering Collaboration</h3><ul className="text-xs text-gray-400 space-y-1.5 list-disc list-inside"><li>Work with engineering to resolve technical issues.</li><li>Communicate customer requirements and challenges.</li><li>Support product improvements based on client insights.</li><li>Document solutions and technical processes.</li></ul></div>
            </div></section>
            <section className="space-y-4"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">Qualifications</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-8"><div className="space-y-3"><h3 className="font-semibold text-white text-xs uppercase tracking-wider text-brand-cyan">Required</h3><ul className="text-xs text-gray-400 space-y-2 list-disc list-inside"><li>Bachelor’s degree in CS, IT, Engineering, or related field.</li><li>Experience in customer success, tech support, or implementations.</li><li>Strong understanding of software applications and SaaS platforms.</li><li>Excellent communication and problem-solving skills.</li><li>Ability to work with technical and non-technical stakeholders.</li></ul></div><div className="space-y-3"><h3 className="font-semibold text-white text-xs uppercase tracking-wider text-brand-indigo">Preferred</h3><ul className="text-xs text-gray-400 space-y-2 list-disc list-inside"><li>Experience in US healthcare or healthcare SaaS environments.</li><li>Familiarity with HIPAA compliance and healthcare workflows.</li><li>Experience supporting EHR/EMR integrations.</li><li>Background in technical account management or implementation.</li><li>Knowledge of healthcare interoperability standards.</li></ul></div></div></section>
            <section className="space-y-4"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">Why Join Med Clinic X?</h2><p className="text-sm text-gray-300 leading-relaxed">At Med Clinic X, you will help healthcare organizations successfully use technology to improve their operations. You will:</p><ul className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs text-gray-400">{['Work directly with healthcare technology customers','Support real-world SaaS implementations','Collaborate with engineering and product teams','Improve customer experiences through technology','Contribute to digital healthcare transformation'].map((item,i)=>(<li key={i} className="flex items-start space-x-2"><CheckCircle className="w-4 h-4 text-brand-emerald shrink-0 mt-0.5" /><span>{item}</span></li>))}</ul></section>
          </motion.div>
        ) : (
          <motion.div key="apply" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-15}} transition={{duration:0.3}} className="lg:col-span-8">
            <div className="glass-panel border border-brand-border rounded-3xl p-6 md:p-8">
              <div className="flex items-center justify-between mb-8 border-b border-brand-border pb-4 font-mono text-[10px]"><div className="flex space-x-4"><span className={formStep===1?'text-brand-cyan font-bold':'text-gray-500'}>01. Profile</span><span className={formStep===2?'text-brand-cyan font-bold':'text-gray-500'}>02. Experience</span><span className={formStep===3?'text-brand-cyan font-bold':'text-gray-500'}>03. Success Sandbox</span><span className={formStep===4?'text-brand-cyan font-bold':'text-gray-500'}>04. Submit</span></div><span className="text-gray-500">Step {formStep} of 4</span></div>
              {submitSuccess ? (<motion.div initial={{opacity:0,scale:0.95}} animate={{opacity:1,scale:1}} className="text-center py-12 space-y-6">
                <div className="w-16 h-16 bg-brand-emerald/10 border border-brand-emerald/20 text-brand-emerald rounded-full flex items-center justify-center mx-auto"><CheckCircle className="w-8 h-8" /></div>
                <div className="space-y-2"><h3 className="font-display font-extrabold text-2xl text-white">Customer Success Pre-screen Completed!</h3><p className="text-sm text-gray-400 max-w-md mx-auto leading-relaxed">Your client triage and integration troubleshooting choices are logged. We verified your Priority-1 support ticket resolution, Epic EHR auth troubleshooting, and proactive churn mitigation strategy.</p></div>
                <button onClick={resetForm} className="inline-flex items-center space-x-2 text-xs font-bold text-brand-cyan hover:underline cursor-pointer"><span>Reset and restart mock screening</span><ArrowRight className="w-3.5 h-3.5" /></button>
              </motion.div>) : (<>
                {formStep===1 && (<div className="space-y-5"><h3 className="font-display font-extrabold text-lg text-white">Let&apos;s start with your basics</h3><div className="space-y-4"><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Full Name <span className="text-red-400">*</span></label><input type="text" required value={formData.name} onChange={(e)=>setFormData(p=>({...p,name:e.target.value}))} placeholder="Alex Chen" className="w-full bg-brand-bg/50 border border-brand-border rounded-xl px-4 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-brand-cyan transition-colors" /></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Email Address <span className="text-red-400">*</span></label><input type="email" required value={formData.email} onChange={(e)=>setFormData(p=>({...p,email:e.target.value}))} placeholder="alex.chen@example.com" className="w-full bg-brand-bg/50 border border-brand-border rounded-xl px-4 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-brand-cyan transition-colors" /></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">GitHub or Portfolio URL</label><input type="url" value={formData.portfolioUrl} onChange={(e)=>setFormData(p=>({...p,portfolioUrl:e.target.value}))} placeholder="https://github.com/alexchen-tech" className="w-full bg-brand-bg/50 border border-brand-border rounded-xl px-4 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-brand-cyan transition-colors" /></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Upload Resume / CV <span className="text-red-400">*</span></label><div onDragOver={handleDragOver} onDrop={handleDrop} className="border-2 border-dashed border-brand-border hover:border-brand-cyan/50 rounded-2xl p-6 text-center bg-white/2 cursor-pointer transition-colors relative"><input type="file" accept=".pdf,.doc,.docx" onChange={handleFileUpload} className="absolute inset-0 opacity-0 cursor-pointer w-full h-full" /><Upload className="w-8 h-8 text-gray-500 mx-auto mb-2" />{formData.resumeName?<p className="text-sm font-semibold text-brand-cyan">{formData.resumeName}</p>:<><p className="text-xs text-gray-300 font-semibold mb-1">Drag and drop your file here, or click to browse</p><p className="text-[10px] text-gray-500">Supports PDF, DOCX, DOC up to 10MB</p></>}</div></div></div><div className="pt-4 flex justify-end"><button type="button" disabled={!formData.name||!formData.email||!formData.resumeName} onClick={()=>setFormStep(2)} className="inline-flex items-center space-x-2 bg-brand-cyan text-brand-bg font-bold px-5 py-3 rounded-xl hover:opacity-90 transition-opacity text-xs disabled:opacity-30 cursor-pointer"><span>Next Step</span><ArrowRight className="w-3.5 h-3.5" /></button></div></div>)}
                {formStep===2 && (<div className="space-y-5"><h3 className="font-display font-extrabold text-lg text-white">Experience Profile</h3><div className="space-y-4"><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Primary Background Focus</label><select value={formData.primaryLang} onChange={(e)=>setFormData(p=>({...p,primaryLang:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-brand-cyan transition-colors"><option value="customer_success_eng">Customer Success Engineering / SaaS Support</option><option value="implementation_ehr">Healthcare IT Implementation Consultant</option><option value="tech_support_saas">Technical Account Management (TAM)</option><option value="solutions_architect_junior">Solutions Engineering & API Integrations</option></select></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Years of Technical Support / Client Facing Experience</label><select value={formData.expYears} onChange={(e)=>setFormData(p=>({...p,expYears:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-brand-cyan transition-colors"><option value="1-3">1 to 3 Years</option><option value="3-5">3 to 5 Years (Recommended)</option><option value="5+">5+ Years</option></select></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Do you have experience supporting HIPAA-regulated clinical systems?</label><div className="flex gap-4">{['yes','no'].map(val=>(<button key={val} type="button" onClick={()=>setFormData(p=>({...p,cloudExp:val}))} className={`flex-1 border text-sm font-semibold py-2.5 rounded-xl capitalize transition-all cursor-pointer ${formData.cloudExp===val?'bg-brand-indigo/15 border-brand-indigo text-white':'border-brand-border text-gray-400 hover:border-gray-500'}`}>{val}</button>))}</div></div></div><div className="pt-4 flex justify-between"><button type="button" onClick={()=>setFormStep(1)} className="inline-flex items-center border border-brand-border text-gray-300 hover:text-white font-semibold px-5 py-3 rounded-xl transition-colors text-xs cursor-pointer">Back</button><button type="button" onClick={()=>setFormStep(3)} className="inline-flex items-center space-x-2 bg-brand-cyan text-brand-bg font-bold px-5 py-3 rounded-xl hover:opacity-90 transition-opacity text-xs cursor-pointer"><span>Proceed to Sandbox</span><ArrowRight className="w-3.5 h-3.5" /></button></div></div>)}
                {formStep===3 && (<div className="space-y-5"><div className="flex justify-between items-start"><div><h3 className="font-display font-extrabold text-lg text-white">Customer Success Support & Integration Sandbox</h3><p className="text-xs text-gray-400 mt-1">Resolve critical tickets, identify EHR authorization bugs, and deploy strategies to increase portal adoption.</p></div><span className="text-[9px] font-bold px-2 py-0.5 bg-brand-cyan/15 text-brand-cyan border border-brand-cyan/20 rounded font-mono">CLIENT / SUCCESS</span></div>
                  <div className="space-y-4 font-sans text-xs">
                    <div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-3"><div className="font-mono text-white text-xs font-semibold flex items-center space-x-2"><span className="w-2 h-2 bg-brand-cyan rounded-full shrink-0" /><span>Scenario 1: Support Ticket Triage</span></div><p className="text-gray-400 italic text-[11px] leading-relaxed">&quot;A client reports that their EHR system is failing to pull patient records, blocking active doctor consultations. How do you prioritize and triage this ticket?&quot;</p><select value={sandboxSetup.supportTriage} onChange={(e)=>setSandboxSetup(p=>({...p,supportTriage:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-lg px-3 py-2 text-xs text-white focus:outline-none focus:border-brand-cyan"><option value="">-- Select Triage Strategy --</option><option value="triage_crit_ehr_block">Classify as a Priority-1 (Critical) ticket. Escalate immediately to the engineering integration leads and notify account management while investigating API gateway status (Correct!)</option><option value="triage_low_next_sprint">Mark it as low priority and ask the client to submit a formal feature request to be evaluated during the next planning sprint</option><option value="triage_customer_dns">Instruct the medical team to reset their routers, configure their DNS, and try refreshing the browser page manually</option></select></div>
                    <div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-3"><div className="font-mono text-white text-xs font-semibold flex items-center space-x-2"><span className="w-2 h-2 bg-brand-indigo rounded-full shrink-0" /><span>Scenario 2: EHR Interoperability Gateway Auth Error</span></div><p className="text-gray-400 italic text-[11px] leading-relaxed">&quot;During onboarding, the client's Epic EHR connection suddenly fails with a '401 Unauthorized' error. How do you resolve this connection issue?&quot;</p><select value={sandboxSetup.integrationTroubleshoot} onChange={(e)=>setSandboxSetup(p=>({...p,integrationTroubleshoot:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-lg px-3 py-2 text-xs text-white focus:outline-none focus:border-brand-cyan"><option value="">-- Select Integration Strategy --</option><option value="epic_credentials_auth">Verify the Client ID and OAuth 2.0 token endpoint configurations, ensure our server IP addresses are whitelisted in Epic's Developer console, and check certificate validity (Correct!)</option><option value="epic_restart_service">Advise the client to restart their Epic physical database servers to clear cached network settings</option><option value="epic_bypass_auth">Configure our API wrapper to bypass OAuth authentication entirely and run the queries over unencrypted HTTP protocol</option></select></div>
                    <div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-3"><div className="font-mono text-white text-xs font-semibold flex items-center space-x-2"><span className="w-2 h-2 bg-brand-emerald rounded-full shrink-0" /><span>Scenario 3: Adoption & Churn Mitigation</span></div><p className="text-gray-400 italic text-[11px] leading-relaxed">&quot;A clinic group has had zero active portal sessions for the last 15 days, showing a high risk of churn. What is the optimal client mitigation action?&quot;</p><select value={sandboxSetup.adoptionChrn} onChange={(e)=>setSandboxSetup(p=>({...p,adoptionChrn:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-lg px-3 py-2 text-xs text-white focus:outline-none focus:border-brand-cyan"><option value="">-- Select Adoption Strategy --</option><option value="proactive_training_audit">Inspect portal login audit logs to spot onboarding errors, and proactively contact the clinic supervisor to offer a targeted workflow training session (Correct!)</option><option value="wait_bill_cycle">Wait until the quarterly billing cycle starts and ask client billing reps if they are still using the SaaS product</option><option value="auto_suspend_tenant">Automatically suspend the clinic's tenant account to save compute resource allocation on our cloud cluster</option></select></div>
                  </div>
                  {sandboxError&&<div className="flex items-start space-x-2.5 p-3.5 bg-red-950/40 border border-red-500/20 text-red-300 rounded-xl text-xs"><AlertCircle className="w-4 h-4 shrink-0 mt-0.5" /><span>{sandboxError}</span></div>}
                  {sandboxSuccess&&<div className="flex items-start space-x-2.5 p-3.5 bg-brand-emerald/10 border border-brand-emerald/20 text-brand-emerald rounded-xl text-xs"><CheckCircle className="w-4 h-4 shrink-0 mt-0.5" /><span>Success Sandbox approved! Ticket triage priority confirmed, Epic EHR auth checks validated, and customer success training outreach plans verified.</span></div>}
                  <div className="pt-4 flex justify-between"><button type="button" onClick={()=>setFormStep(2)} className="inline-flex items-center border border-brand-border text-gray-300 hover:text-white font-semibold px-5 py-3 rounded-xl transition-colors text-xs cursor-pointer">Back</button>{!sandboxSuccess?(<button type="button" onClick={validateSandbox} className="inline-flex items-center space-x-2 bg-brand-cyan text-brand-bg font-bold px-5 py-3 rounded-xl hover:opacity-90 transition-opacity text-xs cursor-pointer"><span>Submit Solutions Assessment ({sandboxAttempts} attempts)</span></button>):(<button type="button" onClick={()=>setFormStep(4)} className="inline-flex items-center space-x-2 bg-gradient-to-r from-brand-cyan to-brand-indigo text-white font-bold px-5 py-3 rounded-xl hover:opacity-95 transition-opacity text-xs cursor-pointer"><span>Proceed to Review</span><ArrowRight className="w-3.5 h-3.5" /></button>)}</div></div>)}
                {formStep===4 && (<div className="space-y-5"><h3 className="font-display font-extrabold text-lg text-white">Review & Submit Application</h3><div className="space-y-4 text-xs font-mono"><div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-2"><p className="text-gray-500 uppercase text-[10px] tracking-wider mb-2 font-bold font-sans">Personal Profile</p><p className="text-gray-300"><span className="text-gray-500 font-sans">Name:</span> {formData.name}</p><p className="text-gray-300"><span className="text-gray-500 font-sans">Email:</span> {formData.email}</p>{formData.portfolioUrl&&<p className="text-gray-300"><span className="text-gray-500 font-sans">GitHub:</span> {formData.portfolioUrl}</p>}<p className="text-gray-300"><span className="text-gray-500 font-sans">Resume:</span> {formData.resumeName}</p></div><div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-2"><p className="text-gray-500 uppercase text-[10px] tracking-wider mb-2 font-bold font-sans">Technical Profile</p><p className="text-gray-300"><span className="text-gray-500 font-sans">Success Focus:</span> <span className="capitalize">{formData.primaryLang.replace('_',' ')}</span></p><p className="text-gray-300"><span className="text-gray-500 font-sans">Experience:</span> {formData.expYears} years</p><p className="text-gray-300"><span className="text-gray-500 font-sans">HIPAA Systems Exp:</span> {formData.cloudExp}</p></div><div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-1.5"><p className="text-gray-500 uppercase text-[10px] tracking-wider mb-2 font-bold font-sans">Solutions Result</p><p className="text-brand-emerald flex items-center space-x-1.5"><CheckCircle className="w-3.5 h-3.5" /><span>Triage, EHR authentication checks, and active churn mitigation approved</span></p></div></div><div className="pt-4 flex justify-between"><button type="button" onClick={()=>setFormStep(3)} className="inline-flex items-center border border-brand-border text-gray-300 hover:text-white font-semibold px-5 py-3 rounded-xl transition-colors text-xs cursor-pointer">Back</button><button type="button" disabled={isSubmitting} onClick={submitApplication} className="inline-flex items-center space-x-2 bg-gradient-to-r from-brand-cyan to-brand-indigo text-white font-bold px-6 py-3 rounded-xl hover:opacity-95 transition-opacity text-xs disabled:opacity-50 cursor-pointer">{isSubmitting?<><div className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" /><span>Submitting application...</span></>:<><Send className="w-3.5 h-3.5" /><span>Submit Application</span></>}</button></div></div>)}
              </>)}
            </div></motion.div>)}
        </AnimatePresence>
        <aside className="lg:col-span-4 space-y-6">
          <div className="glass-panel border border-brand-border rounded-3xl p-6 space-y-6"><h3 className="font-display font-extrabold text-base text-white">Technical Core</h3><div className="flex flex-wrap gap-2">{technicalSkills.map((skill,i)=>(<span key={i} className={`text-[10px] font-semibold px-2.5 py-1 rounded-md border tracking-wide uppercase ${skill.color}`}>{skill.name}</span>))}</div></div>
          <div className="glass-panel border border-brand-border rounded-3xl p-6 space-y-6"><div className="flex items-center space-x-2 text-white"><Shield className="w-4 h-4 text-brand-cyan" /><h3 className="font-display font-extrabold text-base">Systems You Will Work With</h3></div><div className="space-y-4">{techAreas.map((area,i)=>(<div key={i} className="flex space-x-3.5"><div className="w-8 h-8 rounded-xl bg-white/2 border border-white/5 flex items-center justify-center text-brand-cyan shrink-0 mt-0.5">{area.icon}</div><div><h4 className="text-xs font-semibold text-white">{area.title}</h4><p className="text-[11px] text-gray-400 leading-relaxed mt-0.5">{area.desc}</p></div></div>))}</div></div>
        </aside>
      </div>
    </div>
  </div>);
}
