"use client";
import { useState } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowRight, Sparkles, FileText, Shield, Activity, Upload, CheckCircle, Globe, Database, Layers, Send, Code, AlertCircle, BookOpen, PenTool } from "lucide-react";
interface TechSkill { name: string; level: string; color: string; }
interface TechArea { title: string; desc: string; icon: React.ReactNode; }
export default function JobClient() {
  const [activeTab, setActiveTab] = useState<'description'|'apply'>('description');
  const [formStep, setFormStep] = useState(1);
  const [formData, setFormData] = useState({ name:'',email:'',portfolioUrl:'',docTool:'confluence',docYears:'3-5',apiDocExp:'yes',resumeFile:null as File|null,resumeName:'' });
  const [sandboxSetup, setSandboxSetup] = useState({ apiDocFormat:'',versioningStrategy:'',infoArchitecture:'' });
  const [sandboxAttempts, setSandboxAttempts] = useState(0);
  const [sandboxSuccess, setSandboxSuccess] = useState(false);
  const [sandboxError, setSandboxError] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitSuccess, setSubmitSuccess] = useState(false);
  const technicalSkills: TechSkill[] = [
    { name:'Confluence / Notion / GitBook', level:'Required', color:'text-brand-cyan bg-brand-cyan/10 border-brand-cyan/20' },
    { name:'OpenAPI / Swagger Docs', level:'Required', color:'text-brand-indigo bg-brand-indigo/10 border-brand-indigo/20' },
    { name:'Markdown & Structured Formats', level:'Required', color:'text-brand-emerald bg-brand-emerald/10 border-brand-emerald/20' },
    { name:'Technical Writing & Editing', level:'Required', color:'text-purple-400 bg-purple-400/10 border-purple-400/20' },
    { name:'Git / Version Control Basics', level:'Required', color:'text-amber-400 bg-amber-400/10 border-amber-400/20' },
    { name:'UX Writing / Developer Portals', level:'Preferred', color:'text-rose-400 bg-rose-400/10 border-rose-400/20' },
  ];
  const techAreas: TechArea[] = [
    { title:'Healthcare SaaS Platforms', desc:'Document product features, configuration settings, and user workflows for clinical SaaS platforms.', icon:<Globe className="w-5 h-5" /> },
    { title:'API & Integration Systems', desc:'Write OpenAPI specs, endpoint references, and authentication guides for healthcare APIs.', icon:<Code className="w-5 h-5" /> },
    { title:'Patient Portal Applications', desc:'Create end-user guides, onboarding tutorials, and FAQ documentation for patient-facing portals.', icon:<Activity className="w-5 h-5" /> },
    { title:'EHR/EMR Integration Docs', desc:'Document clinical data mapping, FHIR resource schemas, and EHR integration workflows.', icon:<Database className="w-5 h-5" /> },
    { title:'AI Healthcare Solutions', desc:'Explain AI model inputs, outputs, and usage guidelines for healthcare professionals and developers.', icon:<Layers className="w-5 h-5" /> },
    { title:'Clinical Workflow Systems', desc:'Create structured clinical workflow diagrams and step-by-step process documentation for care teams.', icon:<BookOpen className="w-5 h-5" /> },
  ];
  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => { if (e.target.files?.[0]) { const f=e.target.files[0]; setFormData(p=>({...p,resumeFile:f,resumeName:f.name})); } };
  const handleDragOver = (e: React.DragEvent) => { e.preventDefault(); };
  const handleDrop = (e: React.DragEvent) => { e.preventDefault(); if (e.dataTransfer.files?.[0]) { const f=e.dataTransfer.files[0]; setFormData(p=>({...p,resumeFile:f,resumeName:f.name})); } };
  const validateSandbox = () => {
    setSandboxAttempts(p=>p+1);
    const ok1=sandboxSetup.apiDocFormat==='openapi_versioned_spec';
    const ok2=sandboxSetup.versioningStrategy==='semantic_changelog_branch';
    const ok3=sandboxSetup.infoArchitecture==='task_based_hierarchy';
    if(ok1&&ok2&&ok3){setSandboxSuccess(true);setSandboxError('');}
    else{setSandboxSuccess(false);let n=0;if(!ok1)n++;if(!ok2)n++;if(!ok3)n++;setSandboxError('Documentation Sandbox pre-screen failed. '+n+'/3 configurations are non-optimal. Hint: Use OpenAPI 3.0 versioned spec files with $ref components for reusable schemas; adopt semantic versioning with a CHANGELOG.md and branch-per-version Git strategy; and organize docs in a task-based hierarchy with getting-started, concept, how-to, and reference sections.');}
  };
  const submitApplication = async () => { setIsSubmitting(true); await new Promise(r=>setTimeout(r,2000)); setIsSubmitting(false); setSubmitSuccess(true); };
  const resetForm = () => { setFormStep(1);setSubmitSuccess(false);setSandboxSuccess(false);setSandboxAttempts(0);setSandboxSetup({apiDocFormat:'',versioningStrategy:'',infoArchitecture:''});setFormData({name:'',email:'',portfolioUrl:'',docTool:'confluence',docYears:'3-5',apiDocExp:'yes',resumeFile:null,resumeName:''}); };
  return (<div className="relative overflow-hidden min-h-screen">
    <div className="fixed top-0 right-1/4 w-[600px] h-[600px] bg-brand-cyan/5 rounded-full blur-[130px] -z-10 pointer-events-none" />
    <div className="fixed bottom-0 left-1/4 w-[500px] h-[500px] bg-brand-indigo/5 rounded-full blur-[130px] -z-10 pointer-events-none" />
    <div className="max-w-6xl mx-auto px-6 py-12 md:py-16">
      <div className="mb-8 flex items-center space-x-2 text-xs"><Link href="/" className="text-gray-500 hover:text-brand-cyan transition-colors">Home</Link><span className="text-gray-600">/</span><Link href="/careers" className="text-gray-500 hover:text-brand-cyan transition-colors">Careers</Link><span className="text-gray-600">/</span><span className="text-white">Documentation Specialist</span></div>
      <header className="mb-12 relative"><div className="absolute -inset-1 bg-gradient-to-r from-brand-cyan/20 to-brand-indigo/20 rounded-3xl blur-2xl opacity-40 -z-10 pointer-events-none" /><div className="glass-panel border border-brand-border rounded-3xl p-8 md:p-12"><div className="grid grid-cols-1 md:grid-cols-12 gap-8 items-center">
        <div className="md:col-span-8 space-y-6">
          <div className="inline-flex items-center space-x-2 bg-gradient-to-r from-brand-cyan/15 to-brand-indigo/15 border border-brand-cyan/20 rounded-full px-4 py-1.5"><div className="w-1.5 h-1.5 bg-brand-cyan rounded-full animate-pulse" /><span className="text-[10px] font-bold text-brand-cyan uppercase tracking-widest">Technical Writing & Docs</span><Sparkles className="w-3 h-3 text-brand-cyan" /></div>
          <h1 className="font-display font-extrabold text-3xl sm:text-4xl lg:text-5xl text-white leading-tight">Documentation Specialist Careers at Med Clinic X</h1>
          <p className="text-sm md:text-base text-gray-300 max-w-2xl leading-relaxed">Create clear, structured, and developer-friendly documentation for healthcare SaaS APIs, clinical workflows, and patient-facing digital health platforms used across the United States.</p>
          <div className="flex flex-wrap gap-3">
            <span className="inline-flex items-center space-x-1.5 text-xs font-semibold px-3 py-1 bg-white/5 border border-brand-border rounded-lg text-white"><PenTool className="w-3.5 h-3.5 text-brand-cyan" /><span>Clinical Informatics</span></span>
            <span className="inline-flex items-center space-x-1.5 text-xs font-semibold px-3 py-1 bg-white/5 border border-brand-border rounded-lg text-white"><Globe className="w-3.5 h-3.5 text-brand-indigo" /><span>Remote (US Only)</span></span>
            
          </div>
        </div>
        <div className="md:col-span-4 flex justify-start md:justify-end"><button onClick={()=>{setActiveTab('apply');const el=document.getElementById('job-content');if(el)el.scrollIntoView({behavior:'smooth'});}} className="w-full md:w-auto inline-flex items-center justify-center space-x-2 bg-gradient-to-r from-brand-cyan to-brand-indigo text-white font-bold px-8 py-4 rounded-2xl hover:opacity-95 transition-opacity shadow-lg shadow-brand-indigo/10 text-sm cursor-pointer"><span>Apply for this Role</span><ArrowRight className="w-4 h-4" /></button></div>
      </div></div></header>
      <div className="border-b border-brand-border mb-8 flex space-x-8">
        <button onClick={()=>setActiveTab('description')} className={`pb-4 text-sm font-bold border-b-2 transition-all cursor-pointer ${activeTab==='description'?'border-brand-cyan text-brand-cyan':'border-transparent text-gray-400 hover:text-white'}`}>Job Description</button>
        <button onClick={()=>setActiveTab('apply')} className={`pb-4 text-sm font-bold border-b-2 transition-all cursor-pointer ${activeTab==='apply'?'border-brand-cyan text-brand-cyan':'border-transparent text-gray-400 hover:text-white'}`}>Apply Portal</button>
      </div>
      <div id="job-content" className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start"><AnimatePresence mode="wait">
        {activeTab==='description' ? (
          <motion.div key="description" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-15}} transition={{duration:0.3}} className="lg:col-span-8 space-y-10">
            <section className="space-y-4"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">About Med Clinic X</h2><p className="text-sm text-gray-300 leading-relaxed">Med Clinic X is a healthcare technology company building modern digital systems that power healthcare organizations across the United States.</p><p className="text-sm text-gray-300 leading-relaxed">We develop healthcare SaaS platforms, AI-driven healthcare systems, patient portals, telemedicine solutions, automation workflows, and integrated digital health products used by clinics, hospitals, and healthcare providers.</p><p className="text-sm text-gray-300 leading-relaxed">Our mission is to make complex healthcare technology simple, understandable, and accessible through clear and structured documentation.</p></section>
            <section className="space-y-4"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">Job Overview</h2><p className="text-sm text-gray-300 leading-relaxed">We are seeking a <strong>Documentation Specialist</strong> to create, organize, and maintain high-quality technical documentation for healthcare SaaS platforms and digital health systems.</p><p className="text-sm text-gray-300 leading-relaxed">In this role, you will translate complex technical, clinical, and product information into clear documentation for developers, healthcare professionals, and end users. You will work closely with engineering, product, and support teams to ensure all Med Clinic X systems are well-documented and easy to use.</p></section>
            <section className="space-y-6"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">Responsibilities</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="glass-panel border border-brand-border p-5 rounded-2xl space-y-2"><div className="w-7 h-7 bg-brand-cyan/10 border border-brand-cyan/20 rounded-lg flex items-center justify-center text-brand-cyan mb-2"><FileText className="w-4 h-4" /></div><h3 className="font-semibold text-white text-sm">Technical Documentation</h3><ul className="text-xs text-gray-400 space-y-1.5 list-disc list-inside"><li>Create and maintain documentation for healthcare SaaS platforms.</li><li>Document APIs, system architecture, and integration workflows.</li><li>Write clear developer guides and implementation manuals.</li><li>Maintain documentation accuracy across product updates.</li></ul></div>
              <div className="glass-panel border border-brand-border p-5 rounded-2xl space-y-2"><div className="w-7 h-7 bg-brand-indigo/10 border border-brand-indigo/20 rounded-lg flex items-center justify-center text-brand-indigo mb-2"><BookOpen className="w-4 h-4" /></div><h3 className="font-semibold text-white text-sm">Healthcare System Documentation</h3><ul className="text-xs text-gray-400 space-y-1.5 list-disc list-inside"><li>Document clinical workflows and healthcare software features.</li><li>Create user guides for patient portals and healthcare apps.</li><li>Explain EHR/EMR integrations and data workflows.</li><li>Ensure clarity for both technical and non-technical users.</li></ul></div>
              <div className="glass-panel border border-brand-border p-5 rounded-2xl space-y-2"><div className="w-7 h-7 bg-brand-emerald/10 border border-brand-emerald/20 rounded-lg flex items-center justify-center text-brand-emerald mb-2"><Code className="w-4 h-4" /></div><h3 className="font-semibold text-white text-sm">API & Product Documentation</h3><ul className="text-xs text-gray-400 space-y-1.5 list-disc list-inside"><li>Write API documentation for internal and external developers.</li><li>Document system endpoints, authentication, and data structures.</li><li>Maintain structured and searchable documentation systems.</li><li>Collaborate with engineering teams for accuracy.</li></ul></div>
              <div className="glass-panel border border-brand-border p-5 rounded-2xl space-y-2"><div className="w-7 h-7 bg-purple-500/10 border border-purple-500/20 rounded-lg flex items-center justify-center text-purple-400 mb-2"><PenTool className="w-4 h-4" /></div><h3 className="font-semibold text-white text-sm">Collaboration & Quality</h3><ul className="text-xs text-gray-400 space-y-1.5 list-disc list-inside"><li>Work closely with engineers, product managers, and QA teams.</li><li>Gather technical input and convert it into structured content.</li><li>Ensure consistency in tone, structure, and formatting.</li><li>Continuously improve documentation usability.</li></ul></div>
            </div></section>
            <section className="space-y-4"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">Qualifications</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-8"><div className="space-y-3"><h3 className="font-semibold text-white text-xs uppercase tracking-wider text-brand-cyan">Required</h3><ul className="text-xs text-gray-400 space-y-2 list-disc list-inside"><li>Bachelor&apos;s in English, Computer Science, or Information Systems.</li><li>Experience in technical writing or documentation roles.</li><li>Strong ability to simplify complex technical concepts.</li><li>Excellent writing, editing, and communication skills.</li><li>Understanding of software systems or SaaS platforms.</li></ul></div><div className="space-y-3"><h3 className="font-semibold text-white text-xs uppercase tracking-wider text-brand-indigo">Preferred</h3><ul className="text-xs text-gray-400 space-y-2 list-disc list-inside"><li>Experience in US healthcare or healthcare SaaS environments.</li><li>Familiarity with HIPAA compliance documentation standards.</li><li>Experience documenting EHR/EMR systems.</li><li>Exposure to AI healthcare or digital health platforms.</li><li>Background in UX writing or developer portals.</li></ul></div></div></section>
            <section className="space-y-4"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">Why Join Med Clinic X?</h2><p className="text-sm text-gray-300 leading-relaxed">At Med Clinic X, you will help make advanced healthcare technology understandable and usable for everyone. You will:</p><ul className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs text-gray-400">{['Document real healthcare SaaS and AI systems used in the US','Work closely with engineering and product teams','Improve usability through clear technical communication','Support scalable healthcare platforms and APIs','Contribute to better healthcare technology adoption','Shape documentation standards for a growing health tech company'].map((item,i)=>(<li key={i} className="flex items-start space-x-2"><CheckCircle className="w-4 h-4 text-brand-emerald shrink-0 mt-0.5" /><span>{item}</span></li>))}</ul></section>
          </motion.div>
        ) : (
          <motion.div key="apply" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-15}} transition={{duration:0.3}} className="lg:col-span-8">
            <div className="glass-panel border border-brand-border rounded-3xl p-6 md:p-8">
              <div className="flex items-center justify-between mb-8 border-b border-brand-border pb-4 font-mono text-[10px]"><div className="flex space-x-4"><span className={formStep===1?'text-brand-cyan font-bold':'text-gray-500'}>01. Profile</span><span className={formStep===2?'text-brand-cyan font-bold':'text-gray-500'}>02. Experience</span><span className={formStep===3?'text-brand-cyan font-bold':'text-gray-500'}>03. Docs Sandbox</span><span className={formStep===4?'text-brand-cyan font-bold':'text-gray-500'}>04. Submit</span></div><span className="text-gray-500">Step {formStep} of 4</span></div>
              {submitSuccess ? (
                <motion.div initial={{opacity:0,scale:0.95}} animate={{opacity:1,scale:1}} className="text-center py-12 space-y-6">
                  <div className="w-16 h-16 bg-brand-emerald/10 border border-brand-emerald/20 text-brand-emerald rounded-full flex items-center justify-center mx-auto"><CheckCircle className="w-8 h-8" /></div>
                  <div className="space-y-2"><h3 className="font-display font-extrabold text-2xl text-white">Documentation Pre-screen Completed!</h3><p className="text-sm text-gray-400 max-w-md mx-auto leading-relaxed">Your documentation quality score is logged. We verified your OpenAPI spec configuration, semantic versioning strategy, and task-based information architecture approach for healthcare documentation.</p></div>
                  <button onClick={resetForm} className="inline-flex items-center space-x-2 text-xs font-bold text-brand-cyan hover:underline cursor-pointer"><span>Reset and restart mock screening</span><ArrowRight className="w-3.5 h-3.5" /></button>
                </motion.div>
              ) : (<>
                {formStep===1 && (<div className="space-y-5"><h3 className="font-display font-extrabold text-lg text-white">Let&apos;s start with your basics</h3><div className="space-y-4"><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Full Name <span className="text-red-400">*</span></label><input type="text" required value={formData.name} onChange={(e)=>setFormData(p=>({...p,name:e.target.value}))} placeholder="Sam Rivera" className="w-full bg-brand-bg/50 border border-brand-border rounded-xl px-4 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-brand-cyan transition-colors" /></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Email Address <span className="text-red-400">*</span></label><input type="email" required value={formData.email} onChange={(e)=>setFormData(p=>({...p,email:e.target.value}))} placeholder="sam.docs@example.com" className="w-full bg-brand-bg/50 border border-brand-border rounded-xl px-4 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-brand-cyan transition-colors" /></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Portfolio or Writing Samples URL</label><input type="url" value={formData.portfolioUrl} onChange={(e)=>setFormData(p=>({...p,portfolioUrl:e.target.value}))} placeholder="https://docs.example.com or github.com/samrivera" className="w-full bg-brand-bg/50 border border-brand-border rounded-xl px-4 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-brand-cyan transition-colors" /></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Upload Resume / CV <span className="text-red-400">*</span></label><div onDragOver={handleDragOver} onDrop={handleDrop} className="border-2 border-dashed border-brand-border hover:border-brand-cyan/50 rounded-2xl p-6 text-center bg-white/2 cursor-pointer transition-colors relative"><input type="file" accept=".pdf,.doc,.docx" onChange={handleFileUpload} className="absolute inset-0 opacity-0 cursor-pointer w-full h-full" /><Upload className="w-8 h-8 text-gray-500 mx-auto mb-2" />{formData.resumeName?<p className="text-sm font-semibold text-brand-cyan">{formData.resumeName}</p>:<><p className="text-xs text-gray-300 font-semibold mb-1">Drag and drop your file here, or click to browse</p><p className="text-[10px] text-gray-500">Supports PDF, DOCX, DOC up to 10MB</p></>}</div></div></div><div className="pt-4 flex justify-end"><button type="button" disabled={!formData.name||!formData.email||!formData.resumeName} onClick={()=>setFormStep(2)} className="inline-flex items-center space-x-2 bg-brand-cyan text-brand-bg font-bold px-5 py-3 rounded-xl hover:opacity-90 transition-opacity text-xs disabled:opacity-30 cursor-pointer"><span>Next Step</span><ArrowRight className="w-3.5 h-3.5" /></button></div></div>)}
                {formStep===2 && (<div className="space-y-5"><h3 className="font-display font-extrabold text-lg text-white">Documentation Experience Profile</h3><div className="space-y-4"><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Primary Documentation Tool</label><select value={formData.docTool} onChange={(e)=>setFormData(p=>({...p,docTool:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-brand-cyan transition-colors"><option value="confluence">Confluence (Atlassian)</option><option value="notion">Notion</option><option value="gitbook">GitBook</option><option value="readme">ReadMe.io / Stoplight</option><option value="google_docs">Google Docs / Drive</option></select></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Years of Technical Writing / Documentation Experience</label><select value={formData.docYears} onChange={(e)=>setFormData(p=>({...p,docYears:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-brand-cyan transition-colors"><option value="0-2">0 to 2 Years</option><option value="3-5">3 to 5 Years</option><option value="5-8">5 to 8 Years</option><option value="8+">8+ Years</option></select></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Have you written API documentation using OpenAPI or Swagger before?</label><div className="flex gap-4">{['yes','no'].map(val=>(<button key={val} type="button" onClick={()=>setFormData(p=>({...p,apiDocExp:val}))} className={`flex-1 border text-sm font-semibold py-2.5 rounded-xl capitalize transition-all cursor-pointer ${formData.apiDocExp===val?'bg-brand-indigo/15 border-brand-indigo text-white':'border-brand-border text-gray-400 hover:border-gray-500'}`}>{val}</button>))}</div></div></div><div className="pt-4 flex justify-between"><button type="button" onClick={()=>setFormStep(1)} className="inline-flex items-center border border-brand-border text-gray-300 hover:text-white font-semibold px-5 py-3 rounded-xl transition-colors text-xs cursor-pointer">Back</button><button type="button" onClick={()=>setFormStep(3)} className="inline-flex items-center space-x-2 bg-brand-cyan text-brand-bg font-bold px-5 py-3 rounded-xl hover:opacity-90 transition-opacity text-xs cursor-pointer"><span>Proceed to Sandbox</span><ArrowRight className="w-3.5 h-3.5" /></button></div></div>)}
                {formStep===3 && (<div className="space-y-5"><div className="flex justify-between items-start"><div><h3 className="font-display font-extrabold text-lg text-white">Documentation Architecture Sandbox</h3><p className="text-xs text-gray-400 mt-1">Configure an OpenAPI spec structure, define a versioning strategy, and organize a healthcare documentation information architecture.</p></div><span className="text-[9px] font-bold px-2 py-0.5 bg-brand-cyan/15 text-brand-cyan border border-brand-cyan/20 rounded font-mono">API Docs / IA</span></div>
                  <div className="space-y-4 font-sans text-xs">
                    <div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-3"><div className="font-mono text-white text-xs font-semibold flex items-center space-x-2"><span className="w-2 h-2 bg-brand-cyan rounded-full shrink-0" /><span>Challenge 1: API Documentation Format for Healthcare Endpoints</span></div><p className="text-gray-400 italic text-[11px] leading-relaxed">&quot;You are asked to create API documentation for a healthcare platform with 40+ REST endpoints covering patient records, appointments, and prescriptions. Which documentation format and structure should you use?&quot;</p><select value={sandboxSetup.apiDocFormat} onChange={(e)=>setSandboxSetup(p=>({...p,apiDocFormat:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-lg px-3 py-2 text-xs text-white focus:outline-none focus:border-brand-cyan"><option value="">-- Select API Doc Format --</option><option value="openapi_versioned_spec">Write an OpenAPI 3.0 YAML spec with $ref components for reusable schemas, grouped by resource tag, with request/response examples for each endpoint (Correct!)</option><option value="word_doc_table">Document all endpoints in a Word document table listing method, URL, and description for each route</option><option value="readme_only">Write a single README.md file with code blocks showing example curl requests for the most common endpoints</option></select></div>
                    <div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-3"><div className="font-mono text-white text-xs font-semibold flex items-center space-x-2"><span className="w-2 h-2 bg-brand-indigo rounded-full shrink-0" /><span>Challenge 2: Documentation Versioning Strategy</span></div><p className="text-gray-400 italic text-[11px] leading-relaxed">&quot;Your healthcare SaaS platform releases a breaking API change in v2.0 that deprecates 12 v1.0 endpoints. How should you manage documentation versioning to serve both existing and new developer audiences?&quot;</p><select value={sandboxSetup.versioningStrategy} onChange={(e)=>setSandboxSetup(p=>({...p,versioningStrategy:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-lg px-3 py-2 text-xs text-white focus:outline-none focus:border-brand-cyan"><option value="">-- Select Versioning Strategy --</option><option value="semantic_changelog_branch">Maintain parallel versioned doc branches (v1 and v2), add deprecation notices with migration guides in v1, and publish a CHANGELOG.md with a full breaking-change summary (Correct!)</option><option value="overwrite_existing">Overwrite all existing documentation with the v2.0 content and add a one-line note that the API has been updated</option><option value="single_page_all_versions">Combine all versions on one page with inline code comments distinguishing v1 from v2 endpoints</option></select></div>
                    <div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-3"><div className="font-mono text-white text-xs font-semibold flex items-center space-x-2"><span className="w-2 h-2 bg-brand-emerald rounded-full shrink-0" /><span>Challenge 3: Information Architecture for Healthcare SaaS Docs</span></div><p className="text-gray-400 italic text-[11px] leading-relaxed">&quot;You are building a documentation portal for a clinical SaaS platform used by doctors, developers, and hospital IT teams. How should you organize the top-level information architecture?&quot;</p><select value={sandboxSetup.infoArchitecture} onChange={(e)=>setSandboxSetup(p=>({...p,infoArchitecture:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-lg px-3 py-2 text-xs text-white focus:outline-none focus:border-brand-cyan"><option value="">-- Select Information Architecture --</option><option value="task_based_hierarchy">Organize docs into Getting Started, Concepts, How-To Guides, API Reference, and Troubleshooting sections, with audience-based entry paths for developers, clinicians, and IT admins (Correct!)</option><option value="alphabetical_index">List all documentation topics in a single alphabetical index for uniform discoverability across all user types</option><option value="feature_dump">Create one section per product feature with all technical, clinical, and user content mixed together under each feature name</option></select></div>
                  </div>
                  {sandboxError&&<div className="flex items-start space-x-2.5 p-3.5 bg-red-950/40 border border-red-500/20 text-red-300 rounded-xl text-xs"><AlertCircle className="w-4 h-4 shrink-0 mt-0.5" /><span>{sandboxError}</span></div>}
                  {sandboxSuccess&&<div className="flex items-start space-x-2.5 p-3.5 bg-brand-emerald/10 border border-brand-emerald/20 text-brand-emerald rounded-xl text-xs"><CheckCircle className="w-4 h-4 shrink-0 mt-0.5" /><span>Documentation pre-screen approved! OpenAPI 3.0 versioned spec with $ref components confirmed, parallel versioned branch strategy with CHANGELOG validated, and task-based IA with audience-specific entry paths approved.</span></div>}
                  <div className="pt-4 flex justify-between"><button type="button" onClick={()=>setFormStep(2)} className="inline-flex items-center border border-brand-border text-gray-300 hover:text-white font-semibold px-5 py-3 rounded-xl transition-colors text-xs cursor-pointer">Back</button>{!sandboxSuccess?(<button type="button" onClick={validateSandbox} className="inline-flex items-center space-x-2 bg-brand-cyan text-brand-bg font-bold px-5 py-3 rounded-xl hover:opacity-90 transition-opacity text-xs cursor-pointer"><span>Validate Documentation Design ({sandboxAttempts} attempts)</span></button>):(<button type="button" onClick={()=>setFormStep(4)} className="inline-flex items-center space-x-2 bg-gradient-to-r from-brand-cyan to-brand-indigo text-white font-bold px-5 py-3 rounded-xl hover:opacity-95 transition-opacity text-xs cursor-pointer"><span>Proceed to Review</span><ArrowRight className="w-3.5 h-3.5" /></button>)}</div></div>)}
                {formStep===4 && (<div className="space-y-5"><h3 className="font-display font-extrabold text-lg text-white">Review & Submit Application</h3><div className="space-y-4 text-xs font-mono"><div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-2"><p className="text-gray-500 uppercase text-[10px] tracking-wider mb-2 font-bold font-sans">Personal Profile</p><p className="text-gray-300"><span className="text-gray-500 font-sans">Name:</span> {formData.name}</p><p className="text-gray-300"><span className="text-gray-500 font-sans">Email:</span> {formData.email}</p>{formData.portfolioUrl&&<p className="text-gray-300"><span className="text-gray-500 font-sans">Portfolio:</span> {formData.portfolioUrl}</p>}<p className="text-gray-300"><span className="text-gray-500 font-sans">Resume:</span> {formData.resumeName}</p></div><div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-2"><p className="text-gray-500 uppercase text-[10px] tracking-wider mb-2 font-bold font-sans">Documentation Profile</p><p className="text-gray-300"><span className="text-gray-500 font-sans">Primary Tool:</span> <span className="capitalize">{formData.docTool}</span></p><p className="text-gray-300"><span className="text-gray-500 font-sans">Experience:</span> {formData.docYears} years</p><p className="text-gray-300"><span className="text-gray-500 font-sans">API Doc Experience:</span> {formData.apiDocExp}</p></div><div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-1.5"><p className="text-gray-500 uppercase text-[10px] tracking-wider mb-2 font-bold font-sans">Sandbox Result</p><p className="text-brand-emerald flex items-center space-x-1.5"><CheckCircle className="w-3.5 h-3.5" /><span>OpenAPI spec, versioning strategy, and task-based information architecture validated</span></p></div></div><div className="pt-4 flex justify-between"><button type="button" onClick={()=>setFormStep(3)} className="inline-flex items-center border border-brand-border text-gray-300 hover:text-white font-semibold px-5 py-3 rounded-xl transition-colors text-xs cursor-pointer">Back</button><button type="button" disabled={isSubmitting} onClick={submitApplication} className="inline-flex items-center space-x-2 bg-gradient-to-r from-brand-cyan to-brand-indigo text-white font-bold px-6 py-3 rounded-xl hover:opacity-95 transition-opacity text-xs disabled:opacity-50 cursor-pointer">{isSubmitting?<><div className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" /><span>Submitting application...</span></>:<><Send className="w-3.5 h-3.5" /><span>Submit Documentation Application</span></>}</button></div></div>)}
              </>)}
            </div></motion.div>)}
        </AnimatePresence>
        <aside className="lg:col-span-4 space-y-6">
          <div className="glass-panel border border-brand-border rounded-3xl p-6 space-y-6"><h3 className="font-display font-extrabold text-base text-white">Technical Core</h3><div className="flex flex-wrap gap-2">{technicalSkills.map((skill,i)=>(<span key={i} className={`text-[10px] font-semibold px-2.5 py-1 rounded-md border tracking-wide uppercase ${skill.color}`}>{skill.name}</span>))}</div></div>
          <div className="glass-panel border border-brand-border rounded-3xl p-6 space-y-6"><div className="flex items-center space-x-2 text-white"><Shield className="w-4 h-4 text-brand-cyan" /><h3 className="font-display font-extrabold text-base">Systems You Will Document</h3></div><div className="space-y-4">{techAreas.map((area,i)=>(<div key={i} className="flex space-x-3.5"><div className="w-8 h-8 rounded-xl bg-white/2 border border-white/5 flex items-center justify-center text-brand-cyan shrink-0 mt-0.5">{area.icon}</div><div><h4 className="text-xs font-semibold text-white">{area.title}</h4><p className="text-[11px] text-gray-400 leading-relaxed mt-0.5">{area.desc}</p></div></div>))}</div></div>
        </aside>
      </div>
    </div>
  </div>);
}
