import { Metadata } from "next";
import JobClient from "./JobClient";
export const metadata: Metadata = {
  title: "Documentation Specialist Jobs | Med Clinic X Healthcare",
  description: "Join Med Clinic X as a Documentation Specialist. Create clear healthcare SaaS, API, and clinical system documentation for US digital health platforms.",
  keywords: ["Documentation Specialist","Documentation Specialist Jobs USA","Technical Documentation Specialist Healthcare","Healthcare Technical Writer Jobs","SaaS Documentation Specialist Healthcare","API Documentation Writer Healthcare","Clinical Software Documentation Jobs","Digital Health Documentation Specialist","US Healthcare Technical Writer","Healthcare Systems Documentation Jobs"],
  alternates: { canonical: "https://medclinicx.com/careers/documentation-specialist" },
  openGraph: { title: "Documentation Specialist Jobs | Med Clinic X Healthcare", description: "Join Med Clinic X as a Documentation Specialist. Create clear healthcare SaaS, API, and clinical system documentation for US digital health platforms.", url: "https://medclinicx.com/careers/documentation-specialist", images: [{ url: "/og-image.png", width: 1200, height: 630, alt: "Documentation Specialist Job at Med Clinic X" }] },
};
export default function JobPage() {
  const breadcrumb = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://medclinicx.com" },{ "@type": "ListItem", position: 2, name: "Careers", item: "https://medclinicx.com/careers" },{ "@type": "ListItem", position: 3, name: "Documentation Specialist", item: "https://medclinicx.com/careers/documentation-specialist" }] };
  const jobPosting = { "@context": "https://schema.org", "@type": "JobPosting", title: "Documentation Specialist", description: "Create, organize, and maintain high-quality technical documentation for healthcare SaaS platforms and digital health systems across the United States.", datePosted: "2026-06-26", employmentType: "FULL_TIME", hiringOrganization: { "@type": "Organization", name: "Med Clinic X", sameAs: "https://medclinicx.com", logo: "https://medclinicx.com/og-image.png" }, jobLocation: { "@type": "Place", address: { "@type": "PostalAddress", addressLocality: "Austin", addressRegion: "TX", postalCode: "78701", addressCountry: "US" } }, jobLocationType: "TELECOMMUTE", applicantLocationRequirements: { "@type": "Country", name: "United States" } };
  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jobPosting) }} /><JobClient /></>);
}