"use client";
import { useState } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowRight, Sparkles, FileText, Shield, Activity, Upload, CheckCircle, Globe, Database, Layers, Send, Code, AlertCircle, Server, Cpu } from "lucide-react";

interface TechSkill { name: string; level: string; color: string; }
interface TechArea { title: string; desc: string; icon: React.ReactNode; }

export default function JobClient() {
  const [activeTab, setActiveTab] = useState<'description'|'apply'>('description');
  const [formStep, setFormStep] = useState(1);
  const [formData, setFormData] = useState({ name:'',email:'',portfolioUrl:'',primaryLang:'embedded_c_cpp',expYears:'3-5',cloudExp:'yes',resumeFile:null as File|null,resumeName:'' });
  const [sandboxSetup, setSandboxSetup] = useState({ rtosScheduling:'',telemetrySecurity:'',otaVerification:'' });
  const [sandboxAttempts, setSandboxAttempts] = useState(0);
  const [sandboxSuccess, setSandboxSuccess] = useState(false);
  const [sandboxError, setSandboxError] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitSuccess, setSubmitSuccess] = useState(false);

  const technicalSkills: TechSkill[] = [
    { name:'Connected Medical Devices & IoT', level:'Required', color:'text-brand-cyan bg-brand-cyan/10 border-brand-cyan/20' },
    { name:'RTOS Preemptive Scheduling', level:'Required', color:'text-brand-indigo bg-brand-indigo/10 border-brand-indigo/20' },
    { name:'MQTT over TLS 1.3 / mTLS', level:'Required', color:'text-brand-emerald bg-brand-emerald/10 border-brand-emerald/20' },
    { name:'Embedded C/C++ / Python', level:'Required', color:'text-purple-400 bg-purple-400/10 border-purple-400/20' },
    { name:'Secure Boot & OTA updates', level:'Required', color:'text-amber-400 bg-amber-400/10 border-amber-400/20' },
    { name:'Edge Computing & Telemetry', level:'Preferred', color:'text-rose-400 bg-rose-400/10 border-rose-400/20' },
  ];

  const techAreas: TechArea[] = [
    { title:'Healthcare IoT Platforms', desc:'Build scalable telemetry endpoints in the cloud to manage connected diagnostic assets.', icon:<Layers className="w-5 h-5" /> },
    { title:'Remote Patient Monitoring Systems', desc:'Maintain secure links for patient vitals, telemetry streams, and dashboard visualizations.', icon:<Activity className="w-5 h-5" /> },
    { title:'Connected Medical Devices', desc:'Integrate pulse oximeters, ECG patches, and blood pressure monitors with software gates.', icon:<Cpu className="w-5 h-5" /> },
    { title:'EHR/EMR Interoperability', desc:'Connect IoT data streams directly into patient clinical database profiles.', icon:<Database className="w-5 h-5" /> },
    { title:'AI Healthcare Solutions', desc:'Run lightweight anomaly-detection classifiers directly on edge devices to spot critical telemetry shifts.', icon:<Sparkles className="w-5 h-5" /> },
    { title:'Cloud Integration Solutions', desc:'Manage cloud IoT hubs, message routing gateways, and telemetry pipelines.', icon:<Server className="w-5 h-5" /> },
  ];

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => { if (e.target.files?.[0]) { const f=e.target.files[0]; setFormData(p=>({...p,resumeFile:f,resumeName:f.name})); } };
  const handleDragOver = (e: React.DragEvent) => { e.preventDefault(); };
  const handleDrop = (e: React.DragEvent) => { e.preventDefault(); if (e.dataTransfer.files?.[0]) { const f=e.dataTransfer.files[0]; setFormData(p=>({...p,resumeFile:f,resumeName:f.name})); } };

  const validateSandbox = () => {
    setSandboxAttempts(p=>p+1);
    const ok1=sandboxSetup.rtosScheduling==='preemptive_priorities_sensor';
    const ok2=sandboxSetup.telemetrySecurity==='mqtt_tls13_mtls_client';
    const ok3=sandboxSetup.otaVerification==='signed_firmware_enclave';
    if(ok1&&ok2&&ok3){setSandboxSuccess(true);setSandboxError('');}
    else{setSandboxSuccess(false);let n=0;if(!ok1)n++;if(!ok2)n++;if(!ok3)n++;setSandboxError('IoT Engineering pre-screen failed. '+n+'/3 decisions are non-optimal. Hint: Enforce preemptive scheduling priorities on critical sensor loops; secure MQTT channels using TLS 1.3 and client certificates (mTLS); and verify OTA firmware updates via cryptographically signed binaries.');}
  };

  const submitApplication = async () => { setIsSubmitting(true); await new Promise(r=>setTimeout(r,2000)); setIsSubmitting(false); setSubmitSuccess(true); };
  const resetForm = () => { setFormStep(1);setSubmitSuccess(false);setSandboxSuccess(false);setSandboxAttempts(0);setSandboxSetup({rtosScheduling:'',telemetrySecurity:'',otaVerification:''});setFormData({name:'',email:'',portfolioUrl:'',primaryLang:'embedded_c_cpp',expYears:'3-5',cloudExp:'yes',resumeFile:null,resumeName:''}); };

  return (<div className="relative overflow-hidden min-h-screen">
    <div className="fixed top-0 right-1/4 w-[600px] h-[600px] bg-brand-cyan/5 rounded-full blur-[130px] -z-10 pointer-events-none" />
    <div className="fixed bottom-0 left-1/4 w-[500px] h-[500px] bg-brand-indigo/5 rounded-full blur-[130px] -z-10 pointer-events-none" />
    <div className="max-w-6xl mx-auto px-6 py-12 md:py-16">
      <div className="mb-8 flex items-center space-x-2 text-xs"><Link href="/" className="text-gray-500 hover:text-brand-cyan transition-colors">Home</Link><span className="text-gray-600">/</span><Link href="/careers" className="text-gray-500 hover:text-brand-cyan transition-colors">Careers</Link><span className="text-gray-600">/</span><span className="text-white">IoT Developer</span></div>
      <header className="mb-12 relative"><div className="absolute -inset-1 bg-gradient-to-r from-brand-cyan/20 to-brand-indigo/20 rounded-3xl blur-2xl opacity-40 -z-10 pointer-events-none" /><div className="glass-panel border border-brand-border rounded-3xl p-8 md:p-12"><div className="grid grid-cols-1 md:grid-cols-12 gap-8 items-center">
        <div className="md:col-span-8 space-y-6">
          <div className="inline-flex items-center space-x-2 bg-gradient-to-r from-brand-cyan/15 to-brand-indigo/15 border border-brand-cyan/20 rounded-full px-4 py-1.5"><div className="w-1.5 h-1.5 bg-brand-cyan rounded-full animate-pulse" /><span className="text-[10px] font-bold text-brand-cyan uppercase tracking-widest">Medical IoT & Embedded Systems</span><Sparkles className="w-3 h-3 text-brand-cyan" /></div>
          <h1 className="font-display font-extrabold text-3xl sm:text-4xl lg:text-5xl text-white leading-tight">IoT Developer Careers at Med Clinic X</h1>
          <p className="text-sm md:text-base text-gray-300 max-w-2xl leading-relaxed">Design, develop, and integrate connected healthcare technology solutions that improve patient monitoring, healthcare workflows, and digital health experiences.</p>
          <div className="flex flex-wrap gap-3">
            <span className="inline-flex items-center space-x-1.5 text-xs font-semibold px-3 py-1 bg-white/5 border border-brand-border rounded-lg text-white"><Cpu className="w-3.5 h-3.5 text-brand-cyan" /><span>Embedded & IoT</span></span>
            <span className="inline-flex items-center space-x-1.5 text-xs font-semibold px-3 py-1 bg-white/5 border border-brand-border rounded-lg text-white"><Globe className="w-3.5 h-3.5 text-brand-indigo" /><span>Remote (US Only)</span></span>
            
          </div>
        </div>
        <div className="md:col-span-4 flex justify-start md:justify-end"><button onClick={()=>{setActiveTab('apply');const el=document.getElementById('job-content');if(el)el.scrollIntoView({behavior:'smooth'});}} className="w-full md:w-auto inline-flex items-center justify-center space-x-2 bg-gradient-to-r from-brand-cyan to-brand-indigo text-white font-bold px-8 py-4 rounded-2xl hover:opacity-95 transition-opacity shadow-lg shadow-brand-indigo/10 text-sm cursor-pointer"><span>Apply for this Role</span><ArrowRight className="w-4 h-4" /></button></div>
      </div></div></header>
      <div className="border-b border-brand-border mb-8 flex space-x-8">
        <button onClick={()=>setActiveTab('description')} className={`pb-4 text-sm font-bold border-b-2 transition-all cursor-pointer ${activeTab==='description'?'border-brand-cyan text-brand-cyan':'border-transparent text-gray-400 hover:text-white'}`}>Job Description</button>
        <button onClick={()=>setActiveTab('apply')} className={`pb-4 text-sm font-bold border-b-2 transition-all cursor-pointer ${activeTab==='apply'?'border-brand-cyan text-brand-cyan':'border-transparent text-gray-400 hover:text-white'}`}>Apply Portal</button>
      </div>
      <div id="job-content" className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start"><AnimatePresence mode="wait">
        {activeTab==='description' ? (
          <motion.div key="description" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-15}} transition={{duration:0.3}} className="lg:col-span-8 space-y-10">
            <section className="space-y-4"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">About Med Clinic X</h2><p className="text-sm text-gray-300 leading-relaxed">Med Clinic X is a healthcare technology company creating innovative digital health solutions that connect healthcare providers, patients, and technology systems across the United States.</p><p className="text-sm text-gray-300 leading-relaxed">We develop healthcare SaaS platforms, AI-driven healthcare solutions, patient portals, telemedicine systems, automation workflows, and connected healthcare technology products for clinics, hospitals, and medical organizations.</p><p className="text-sm text-gray-300 leading-relaxed">Our mission is to build smarter healthcare experiences through secure, connected, and intelligent technology.</p></section>
            <section className="space-y-4"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">Job Overview</h2><p className="text-sm text-gray-300 leading-relaxed">We are seeking an <strong>IoT Developer</strong> to design, develop, and integrate connected healthcare technology solutions that improve patient monitoring, healthcare workflows, and digital health experiences.</p><p className="text-sm text-gray-300 leading-relaxed">In this role, you will work on IoT platforms, device integrations, data communication systems, and healthcare technology applications that connect physical devices with cloud-based healthcare platforms. You will collaborate with software engineers, cloud teams, and healthcare technology specialists to build reliable IoT solutions.</p></section>
            <section className="space-y-6"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">Responsibilities</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="glass-panel border border-brand-border p-5 rounded-2xl space-y-2"><div className="w-7 h-7 bg-brand-cyan/10 border border-brand-cyan/20 rounded-lg flex items-center justify-center text-brand-cyan mb-2"><Cpu className="w-4 h-4" /></div><h3 className="font-semibold text-white text-sm">Healthcare IoT Development</h3><ul className="text-xs text-gray-400 space-y-1.5 list-disc list-inside"><li>Design and develop IoT solutions for clinical monitoring.</li><li>Build interfaces linking medical devices to cloud portals.</li><li>Develop device communication channels and data streams.</li><li>Support remote patient vitals monitoring telemetry systems.</li></ul></div>
              <div className="glass-panel border border-brand-border p-5 rounded-2xl space-y-2"><div className="w-7 h-7 bg-brand-indigo/10 border border-brand-indigo/20 rounded-lg flex items-center justify-center text-brand-indigo mb-2"><Database className="w-4 h-4" /></div><h3 className="font-semibold text-white text-sm">Device Integration & Data Processing</h3><ul className="text-xs text-gray-400 space-y-1.5 list-disc list-inside"><li>Integrate telemetry feeds with central backend platforms.</li><li>Process device-generated streams securely and validate bounds.</li><li>Build robust APIs for IoT peripheral device authentication.</li><li>Ensure zero-loss data exchange between edge and cloud.</li></ul></div>
              <div className="glass-panel border border-brand-border p-5 rounded-2xl space-y-2"><div className="w-7 h-7 bg-brand-emerald/10 border border-brand-emerald/20 rounded-lg flex items-center justify-center text-brand-emerald mb-2"><Server className="w-4 h-4" /></div><h3 className="font-semibold text-white text-sm">Cloud & Platform Development</h3><ul className="text-xs text-gray-400 space-y-1.5 list-disc list-inside"><li>Work with cloud IoT services (AWS IoT / Azure IoT).</li><li>Develop scalable IoT backend routing microservices.</li><li>Support high-frequency real-time vitals data ingest.</li><li>Optimize network latency and memory usage on edge nodes.</li></ul></div>
              <div className="glass-panel border border-brand-border p-5 rounded-2xl space-y-2"><div className="w-7 h-7 bg-purple-500/10 border border-purple-500/20 rounded-lg flex items-center justify-center text-purple-400 mb-2"><Shield className="w-4 h-4" /></div><h3 className="font-semibold text-white text-sm">Security & Quality</h3><ul className="text-xs text-gray-400 space-y-1.5 list-disc list-inside"><li>Implement mutual authentication (mTLS) for devices.</li><li>Support secure credentials and HIPAA data controls on flash.</li><li>Troubleshoot firmware bugs, connection losses, and OTA failures.</li><li>Maintain system architecture logs and API specs.</li></ul></div>
            </div></section>
            <section className="space-y-4"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">Qualifications</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-8"><div className="space-y-3"><h3 className="font-semibold text-white text-xs uppercase tracking-wider text-brand-cyan">Required</h3><ul className="text-xs text-gray-400 space-y-2 list-disc list-inside"><li>Bachelor’s in CS, Software Engineering, Electrical Engineering, or related.</li><li>Experience developing IoT applications or connected embedded systems.</li><li>Strong programming skills in Python, C/C++, Java, or JavaScript.</li><li>Deep understanding of device communication protocols (MQTT, HTTP, BLE).</li><li>Excellent hardware troubleshooting and telemetry design skills.</li></ul></div><div className="space-y-3"><h3 className="font-semibold text-white text-xs uppercase tracking-wider text-brand-indigo">Preferred</h3><ul className="text-xs text-gray-400 space-y-2 list-disc list-inside"><li>Experience in healthcare IoT or medical device environments.</li><li>Familiarity with remote patient monitoring (RPM) architectures.</li><li>Knowledge of HIPAA rules and secure boot flash configurations.</li><li>Experience with edge computing algorithms or ML classifiers.</li><li>Knowledge of medical data formats and integration APIs.</li></ul></div></div></section>
            <section className="space-y-4"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">Why Join Med Clinic X?</h2><p className="text-sm text-gray-300 leading-relaxed">At Med Clinic X, you will help build the connected healthcare systems of the future. You will:</p><ul className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs text-gray-400">{['Develop technology supporting modern healthcare delivery','Work on connected healthcare platforms','Collaborate with cloud, AI, and software teams','Build solutions that improve patient experiences','Contribute to digital health innovation in the US market'].map((item,i)=>(<li key={i} className="flex items-start space-x-2"><CheckCircle className="w-4 h-4 text-brand-emerald shrink-0 mt-0.5" /><span>{item}</span></li>))}</ul></section>
          </motion.div>
        ) : (
          <motion.div key="apply" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-15}} transition={{duration:0.3}} className="lg:col-span-8">
            <div className="glass-panel border border-brand-border rounded-3xl p-6 md:p-8">
              <div className="flex items-center justify-between mb-8 border-b border-brand-border pb-4 font-mono text-[10px]"><div className="flex space-x-4"><span className={formStep===1?'text-brand-cyan font-bold':'text-gray-500'}>01. Profile</span><span className={formStep===2?'text-brand-cyan font-bold':'text-gray-500'}>02. Experience</span><span className={formStep===3?'text-brand-cyan font-bold':'text-gray-500'}>03. Embedded Sandbox</span><span className={formStep===4?'text-brand-cyan font-bold':'text-gray-500'}>04. Submit</span></div><span className="text-gray-500">Step {formStep} of 4</span></div>
              {submitSuccess ? (<motion.div initial={{opacity:0,scale:0.95}} animate={{opacity:1,scale:1}} className="text-center py-12 space-y-6">
                <div className="w-16 h-16 bg-brand-emerald/10 border border-brand-emerald/20 text-brand-emerald rounded-full flex items-center justify-center mx-auto"><CheckCircle className="w-8 h-8" /></div>
                <div className="space-y-2"><h3 className="font-display font-extrabold text-2xl text-white">IoT Embedded Pre-screen Completed!</h3><p className="text-sm text-gray-400 max-w-md mx-auto leading-relaxed">Your device scheduling, data security, and firmware deployment designs are logged. We verified your preemptive sensor priorities, mutual authentication (mTLS) MQTT telemetry channels, and Secure Boot signature verification keys.</p></div>
                <button onClick={resetForm} className="inline-flex items-center space-x-2 text-xs font-bold text-brand-cyan hover:underline cursor-pointer"><span>Reset and restart mock screening</span><ArrowRight className="w-3.5 h-3.5" /></button>
              </motion.div>) : (<>
                {formStep===1 && (<div className="space-y-5"><h3 className="font-display font-extrabold text-lg text-white">Let&apos;s start with your basics</h3><div className="space-y-4"><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Full Name <span className="text-red-400">*</span></label><input type="text" required value={formData.name} onChange={(e)=>setFormData(p=>({...p,name:e.target.value}))} placeholder="Morgan Lee" className="w-full bg-brand-bg/50 border border-brand-border rounded-xl px-4 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-brand-cyan transition-colors" /></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Email Address <span className="text-red-400">*</span></label><input type="email" required value={formData.email} onChange={(e)=>setFormData(p=>({...p,email:e.target.value}))} placeholder="morgan.lee@example.com" className="w-full bg-brand-bg/50 border border-brand-border rounded-xl px-4 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-brand-cyan transition-colors" /></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">GitHub or Portfolio URL</label><input type="url" value={formData.portfolioUrl} onChange={(e)=>setFormData(p=>({...p,portfolioUrl:e.target.value}))} placeholder="https://github.com/morganlee-iot" className="w-full bg-brand-bg/50 border border-brand-border rounded-xl px-4 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-brand-cyan transition-colors" /></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Upload Resume / CV <span className="text-red-400">*</span></label><div onDragOver={handleDragOver} onDrop={handleDrop} className="border-2 border-dashed border-brand-border hover:border-brand-cyan/50 rounded-2xl p-6 text-center bg-white/2 cursor-pointer transition-colors relative"><input type="file" accept=".pdf,.doc,.docx" onChange={handleFileUpload} className="absolute inset-0 opacity-0 cursor-pointer w-full h-full" /><Upload className="w-8 h-8 text-gray-500 mx-auto mb-2" />{formData.resumeName?<p className="text-sm font-semibold text-brand-cyan">{formData.resumeName}</p>:<><p className="text-xs text-gray-300 font-semibold mb-1">Drag and drop your file here, or click to browse</p><p className="text-[10px] text-gray-500">Supports PDF, DOCX, DOC up to 10MB</p></>}</div></div></div><div className="pt-4 flex justify-end"><button type="button" disabled={!formData.name||!formData.email||!formData.resumeName} onClick={()=>setFormStep(2)} className="inline-flex items-center space-x-2 bg-brand-cyan text-brand-bg font-bold px-5 py-3 rounded-xl hover:opacity-90 transition-opacity text-xs disabled:opacity-30 cursor-pointer"><span>Next Step</span><ArrowRight className="w-3.5 h-3.5" /></button></div></div>)}
                {formStep===2 && (<div className="space-y-5"><h3 className="font-display font-extrabold text-lg text-white">Experience Profile</h3><div className="space-y-4"><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Primary Embedded Focus</label><select value={formData.primaryLang} onChange={(e)=>setFormData(p=>({...p,primaryLang:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-brand-cyan transition-colors"><option value="embedded_c_cpp">Embedded C / C++ Peripheral Development</option><option value="python_iot">Python Microcontroller Scripting & Local Logic</option><option value="rtos_systems">Real-Time Operating Systems (RTOS / FreeRTOS)</option><option value="cloud_iot_integrations">Cloud IoT Integration Pipelines (AWS / Azure Hubs)</option></select></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Years of IoT / Hardware Development Experience</label><select value={formData.expYears} onChange={(e)=>setFormData(p=>({...p,expYears:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-brand-cyan transition-colors"><option value="1-3">1 to 3 Years</option><option value="3-5">3 to 5 Years (Recommended)</option><option value="5+">5+ Years</option></select></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Do you have experience developing firmware for HIPAA-regulated medical devices?</label><div className="flex gap-4">{['yes','no'].map(val=>(<button key={val} type="button" onClick={()=>setFormData(p=>({...p,cloudExp:val}))} className={`flex-1 border text-sm font-semibold py-2.5 rounded-xl capitalize transition-all cursor-pointer ${formData.cloudExp===val?'bg-brand-indigo/15 border-brand-indigo text-white':'border-brand-border text-gray-400 hover:border-gray-500'}`}>{val}</button>))}</div></div></div><div className="pt-4 flex justify-between"><button type="button" onClick={()=>setFormStep(1)} className="inline-flex items-center border border-brand-border text-gray-300 hover:text-white font-semibold px-5 py-3 rounded-xl transition-colors text-xs cursor-pointer">Back</button><button type="button" onClick={()=>setFormStep(3)} className="inline-flex items-center space-x-2 bg-brand-cyan text-brand-bg font-bold px-5 py-3 rounded-xl hover:opacity-90 transition-opacity text-xs cursor-pointer"><span>Proceed to Sandbox</span><ArrowRight className="w-3.5 h-3.5" /></button></div></div>)}
                {formStep===3 && (<div className="space-y-5"><div className="flex justify-between items-start"><div><h3 className="font-display font-extrabold text-lg text-white">Healthcare IoT & Embedded Sandbox</h3><p className="text-xs text-gray-400 mt-1">Configure preemptive priorities, secure device telemetry, and set secure firmware updating keys.</p></div><span className="text-[9px] font-bold px-2 py-0.5 bg-brand-cyan/15 text-brand-cyan border border-brand-cyan/20 rounded font-mono">EMBEDDED / IOT</span></div>
                  <div className="space-y-4 font-sans text-xs">
                    <div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-3"><div className="font-mono text-white text-xs font-semibold flex items-center space-x-2"><span className="w-2 h-2 bg-brand-cyan rounded-full shrink-0" /><span>Scenario 1: RTOS Task Priorities</span></div><p className="text-gray-400 italic text-[11px] leading-relaxed">&quot;You are developing firmware for a connected patient vital monitor on a real-time OS (RTOS). How do you prioritize tasks for critical heart rate sensors versus battery status updates?&quot;</p><select value={sandboxSetup.rtosScheduling} onChange={(e)=>setSandboxSetup(p=>({...p,rtosScheduling:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-lg px-3 py-2 text-xs text-white focus:outline-none focus:border-brand-cyan"><option value="">-- Select RTOS Priority Mapping --</option><option value="preemptive_priorities_sensor">Assign critical vital sensor collections and alarm thresholds to high-priority preemptive threads, and assign battery checks to low-priority background workers (Correct!)</option><option value="equal_priorities_threads">Configure all threads to run under the same priority level using simple round-robin scheduling algorithms</option><option value="battery_high_priority">Set battery status polling tasks to high priority to ensure power levels are always reported instantly</option></select></div>
                    <div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-3"><div className="font-mono text-white text-xs font-semibold flex items-center space-x-2"><span className="w-2 h-2 bg-brand-indigo rounded-full shrink-0" /><span>Scenario 2: Secure Telemetry Channel Design</span></div><p className="text-gray-400 italic text-[11px] leading-relaxed">&quot;Our remote patient monitoring devices transmit continuous ECG telemetry data to the cloud. How do you design this telemetry channel for security and low latency?&quot;</p><select value={sandboxSetup.telemetrySecurity} onChange={(e)=>setSandboxSetup(p=>({...p,telemetrySecurity:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-lg px-3 py-2 text-xs text-white focus:outline-none focus:border-brand-cyan"><option value="">-- Select Telemetry Security Protocol --</option><option value="mqtt_tls13_mtls_client">Deploy MQTT telemetry streams over TLS 1.3 with client X.509 certificates (mTLS) for mutual device/server authentication, utilizing QoS level 1 (Correct!)</option><option value="http_unencrypted_get">Transmit the continuous ECG parameters via unencrypted HTTP GET requests to minimize device processing overhead</option><option value="tcp_raw_no_auth">Transmit the data over raw TCP sockets without encryption or authentication filters to maximize throughput</option></select></div>
                    <div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-3"><div className="font-mono text-white text-xs font-semibold flex items-center space-x-2"><span className="w-2 h-2 bg-brand-emerald rounded-full shrink-0" /><span>Scenario 3: Secure Boot & OTA Firmware Updates</span></div><p className="text-gray-400 italic text-[11px] leading-relaxed">&quot;We need to deploy a firmware patch to thousands of active medical monitoring devices over-the-air. How do you guarantee the integrity and source of the update package?&quot;</p><select value={sandboxSetup.otaVerification} onChange={(e)=>setSandboxSetup(p=>({...p,otaVerification:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-lg px-3 py-2 text-xs text-white focus:outline-none focus:border-brand-cyan"><option value="">-- Select OTA Verification Method --</option><option value="signed_firmware_enclave">Enforce hardware Secure Boot checking: verify the firmware payload using a cryptographically signed binary checked by device-level enclave security anchors (Correct!)</option><option value="http_pull_unverified">Configure devices to pull any raw binary file hosted on a public HTTP server endpoint and flash it directly to memory</option><option value="bypass_flash_checks">Disable standard flash checksum checks on the device to prevent local firmware upgrade errors</option></select></div>
                  </div>
                  {sandboxError&&<div className="flex items-start space-x-2.5 p-3.5 bg-red-950/40 border border-red-500/20 text-red-300 rounded-xl text-xs"><AlertCircle className="w-4 h-4 shrink-0 mt-0.5" /><span>{sandboxError}</span></div>}
                  {sandboxSuccess&&<div className="flex items-start space-x-2.5 p-3.5 bg-brand-emerald/10 border border-brand-emerald/20 text-brand-emerald rounded-xl text-xs"><CheckCircle className="w-4 h-4 shrink-0 mt-0.5" /><span>Success Sandbox approved! Preemptive task scheduling confirmed, TLS telemetry channel mutual auth validated, and cryptographically signed OTA configurations verified.</span></div>}
                  <div className="pt-4 flex justify-between"><button type="button" onClick={()=>setFormStep(2)} className="inline-flex items-center border border-brand-border text-gray-300 hover:text-white font-semibold px-5 py-3 rounded-xl transition-colors text-xs cursor-pointer">Back</button>{!sandboxSuccess?(<button type="button" onClick={validateSandbox} className="inline-flex items-center space-x-2 bg-brand-cyan text-brand-bg font-bold px-5 py-3 rounded-xl hover:opacity-90 transition-opacity text-xs cursor-pointer"><span>Submit IoT Assessment ({sandboxAttempts} attempts)</span></button>):(<button type="button" onClick={()=>setFormStep(4)} className="inline-flex items-center space-x-2 bg-gradient-to-r from-brand-cyan to-brand-indigo text-white font-bold px-5 py-3 rounded-xl hover:opacity-95 transition-opacity text-xs cursor-pointer"><span>Proceed to Review</span><ArrowRight className="w-3.5 h-3.5" /></button>)}</div></div>)}
                {formStep===4 && (<div className="space-y-5"><h3 className="font-display font-extrabold text-lg text-white">Review & Submit Application</h3><div className="space-y-4 text-xs font-mono"><div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-2"><p className="text-gray-500 uppercase text-[10px] tracking-wider mb-2 font-bold font-sans">Personal Profile</p><p className="text-gray-300"><span className="text-gray-500 font-sans">Name:</span> {formData.name}</p><p className="text-gray-300"><span className="text-gray-500 font-sans">Email:</span> {formData.email}</p>{formData.portfolioUrl&&<p className="text-gray-300"><span className="text-gray-500 font-sans">Portfolio:</span> {formData.portfolioUrl}</p>}<p className="text-gray-300"><span className="text-gray-500 font-sans">Resume:</span> {formData.resumeName}</p></div><div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-2"><p className="text-gray-500 uppercase text-[10px] tracking-wider mb-2 font-bold font-sans">Technical Profile</p><p className="text-gray-300"><span className="text-gray-500 font-sans">Primary Focus:</span> <span className="capitalize">{formData.primaryLang.replace('_',' ')}</span></p><p className="text-gray-300"><span className="text-gray-500 font-sans">Experience:</span> {formData.expYears} years</p><p className="text-gray-300"><span className="text-gray-500 font-sans">Medical Device Exp:</span> {formData.cloudExp}</p></div><div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-1.5"><p className="text-gray-500 uppercase text-[10px] tracking-wider mb-2 font-bold font-sans">Solutions Result</p><p className="text-brand-emerald flex items-center space-x-1.5"><CheckCircle className="w-3.5 h-3.5" /><span>RTOS preemptive threads, mTLS MQTT streams, and secure boot verify locks approved</span></p></div></div><div className="pt-4 flex justify-between"><button type="button" onClick={()=>setFormStep(3)} className="inline-flex items-center border border-brand-border text-gray-300 hover:text-white font-semibold px-5 py-3 rounded-xl transition-colors text-xs cursor-pointer">Back</button><button type="button" disabled={isSubmitting} onClick={submitApplication} className="inline-flex items-center space-x-2 bg-gradient-to-r from-brand-cyan to-brand-indigo text-white font-bold px-6 py-3 rounded-xl hover:opacity-95 transition-opacity text-xs disabled:opacity-50 cursor-pointer">{isSubmitting?<><div className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" /><span>Submitting application...</span></>:<><Send className="w-3.5 h-3.5" /><span>Submit Application</span></>}</button></div></div>)}
              </>)}
            </div></motion.div>)}
        </AnimatePresence>
        <aside className="lg:col-span-4 space-y-6">
          <div className="glass-panel border border-brand-border rounded-3xl p-6 space-y-6"><h3 className="font-display font-extrabold text-base text-white">Technical Core</h3><div className="flex flex-wrap gap-2">{technicalSkills.map((skill,i)=>(<span key={i} className={`text-[10px] font-semibold px-2.5 py-1 rounded-md border tracking-wide uppercase ${skill.color}`}>{skill.name}</span>))}</div></div>
          <div className="glass-panel border border-brand-border rounded-3xl p-6 space-y-6"><div className="flex items-center space-x-2 text-white"><Shield className="w-4 h-4 text-brand-cyan" /><h3 className="font-display font-extrabold text-base">Systems You Will Work With</h3></div><div className="space-y-4">{techAreas.map((area,i)=>(<div key={i} className="flex space-x-3.5"><div className="w-8 h-8 rounded-xl bg-white/2 border border-white/5 flex items-center justify-center text-brand-cyan shrink-0 mt-0.5">{area.icon}</div><div><h4 className="text-xs font-semibold text-white">{area.title}</h4><p className="text-[11px] text-gray-400 leading-relaxed mt-0.5">{area.desc}</p></div></div>))}</div></div>
        </aside>
      </div>
    </div>
  </div>);
}
