export interface SolutionItem {
  id: string;
  title: string;
  category: "Clinical AI & Automation" | "Patient Portals & Engagement" | "Practice Operations" | "Growth & Marketing";
  iconName: string;
  desc: string;
  href: string;
  badge?: string;
  features: string[];
  image: string;
  stat: string;
  statLabel: string;
}

export const solutionsData: SolutionItem[] = [
  {
    id: "ai-patient-portal",
    title: "AI Patient Portal Platform",
    category: "Patient Portals & Engagement",
    iconName: "HeartPulse",
    desc: "An intelligent, secure patient dashboard featuring automated medical report explanations, interactive health timelines, and integrated care team messaging.",
    href: "/solutions/ai-patient-portal",
    badge: "Flagship",
    features: ["AI Health Companion Chat", "Visual Health Timelines", "PDF Medical Report Readers"],
    image: "/service_patient_portal.png",
    stat: "87/100",
    statLabel: "Average Patient Health Score",
  },
  {
    id: "smart-dental-portal",
    title: "Smart Dental Patient Portal",
    category: "Patient Portals & Engagement",
    iconName: "Smile",
    desc: "Purpose-built portal for dental practices, offering 3D CBCT/X-ray scans storage, orthodontic progress sliders, and clear aligner schedules.",
    href: "/solutions/smart-dental-portal",
    badge: "Specialized",
    features: ["DICOM 3D Scan Storage", "Aligner Trackers", "Installment Plan Invoicing"],
    image: "/service_patient_portal.png",
    stat: "94%",
    statLabel: "Dental Patient Engagement",
  },
  {
    id: "ai-medical-receptionist",
    title: "AI Medical Receptionist System",
    category: "Clinical AI & Automation",
    iconName: "Phone",
    desc: "Voice and chat AI coordinators managing incoming phone queues, routing clinic questions, and booking appointments 24/7.",
    href: "/solutions/ai-medical-receptionist",
    badge: "Hot Automation",
    features: ["Speech-to-Text Call Routing", "24/7 Calendar Syncing", "Multi-lingual Intake Chats"],
    image: "/ai_healthcare_assistant.png",
    stat: "2.4 mins",
    statLabel: "Average Check-in Saved",
  },
  {
    id: "telemedicine-consultation-platform",
    title: "Telemedicine Consultation Platform",
    category: "Patient Portals & Engagement",
    iconName: "Video",
    desc: "Encrypted browser-native video consultation corridors with live vitals telemetry ingestion and digital prescription networks routing.",
    href: "/solutions/telemedicine-consultation-platform",
    badge: "Care Gateway",
    features: ["WebRTC P2P Video Rooms", "Bluetooth Vitals Syncing", "Pharmacy E-Prescribing"],
    image: "/service_telemedicine.png",
    stat: "<120ms",
    statLabel: "Streaming Audio Latency",
  },
  {
    id: "virtual-clinic-os",
    title: "Virtual Clinic OS",
    category: "Practice Operations",
    iconName: "LayoutDashboard",
    desc: "A unified operating system for digital-first clinics, combining electronic patient charts, billing, and scheduling workflows.",
    href: "/solutions/virtual-clinic-os",
    badge: "Full Suite",
    features: ["Unified Clinic Dashboards", "Integrated EHR Systems", "Multi-provider Scheduling"],
    image: "/hw_hero_dashboard.png",
    stat: "99.9%",
    statLabel: "System Uptime Guarantee",
  },
  {
    id: "ai-healthcare-navigator",
    title: "AI Healthcare Navigator",
    category: "Clinical AI & Automation",
    iconName: "Brain",
    desc: "Conversational intake agent that triages patient symptoms, maps concerns to clinical departments, and builds pre-visit briefs for doctors.",
    href: "/solutions/ai-healthcare-navigator",
    badge: "Symptom Intelligence",
    features: ["Conversational Triage", "Emergency Red-flags Screening", "Pre-consult Doctor Briefs"],
    image: "/llm_healthcare_hero.png",
    stat: "50%",
    statLabel: "Onboarding Time Reclaimed",
  },
  {
    id: "careflow-ai",
    title: "CareFlow AI Growth CRM",
    category: "Growth & Marketing",
    iconName: "TrendingUp",
    desc: "Healthcare-tuned customer relationship manager that tracks patient acquisition loops, marketing campaigns, and booking conversion channels.",
    href: "/solutions/careflow-ai",
    badge: "Practice ROI",
    features: ["Intake Lead Scoring", "Automated SMS Recalls", "Multi-Clinic Org Support"],
    image: "/blog_lead_gen.png",
    stat: "35%",
    statLabel: "Average Lead Conversion",
  },
  {
    id: "carematch-ai",
    title: "CareMatch AI Marketplace",
    category: "Growth & Marketing",
    iconName: "Users",
    desc: "Patient-to-provider matching directories scoring doctor compatibility based on clinical concerns, insurance, and open schedule slots.",
    href: "/solutions/carematch-ai",
    badge: "Patient Acquisition",
    features: ["Symptom Matchmaking AI", "Smart Waitlist Refillers", "Stripe Escrow Payments"],
    image: "/hw_patient_journey.png",
    stat: "96.4%",
    statLabel: "Matching Precision Index",
  },
  {
    id: "health-os",
    title: "Specialty Clinic Growth OS",
    category: "Growth & Marketing",
    iconName: "Activity",
    desc: "The ultimate growth engine tailored specifically for IVF, cosmetic, skin, and ophthalmic practices to maximize treatment acceptance and retention.",
    href: "/solutions/health-os",
    badge: "Ultimate Specialty",
    features: ["Visual Health Timelines", "AI Patient Journey Scoring", "Specialty Intake Builders"],
    image: "/healthcare_ux_mockup.png",
    stat: "34%+",
    statLabel: "Treatment Acceptance Rise",
  },
  {
    id: "intake-flow",
    title: "IntakeFlow AI Onboarding",
    category: "Clinical AI & Automation",
    iconName: "FileText",
    desc: "Autopilot onboarding workflows replacing clipboard paper forms with conversational digital questionnaires and automatic EHR record loading.",
    href: "/solutions/intake-flow",
    badge: "Intake Standard",
    features: ["FHIR Schema Intakes", "E-signature Ingestion", "Consent Logs Locking"],
    image: "/blog_predictive_scheduling.png",
    stat: "82%",
    statLabel: "Paper Intake Reduction",
  },
  {
    id: "medi-sync",
    title: "MediSync AI Data Platform",
    category: "Practice Operations",
    iconName: "Database",
    desc: "Secure middleware platform facilitating bidirectional database synchronization between isolated EHR systems, SaaS applications, and FHIR servers.",
    href: "/solutions/medi-sync",
    badge: "Data Hub",
    features: ["HL7 FHIR Gateways", "RLS Database Isolation", "Append-Only Audit Logs"],
    image: "/blog_hipaa_datastore.png",
    stat: "100%",
    statLabel: "Interoperability Score",
  }
];
