"use client";
import { useState } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowRight, Sparkles, FileText, Shield, Activity, Upload, CheckCircle, Globe, Database, Layers, Send, Code, AlertCircle, Server, Cpu } from "lucide-react";

interface TechSkill { name: string; level: string; color: string; }
interface TechArea { title: string; desc: string; icon: React.ReactNode; }

export default function JobClient() {
  const [activeTab, setActiveTab] = useState<'description'|'apply'>('description');
  const [formStep, setFormStep] = useState(1);
  const [formData, setFormData] = useState({ name:'',email:'',portfolioUrl:'',primaryLang:'app_architecture',expYears:'8+',cloudExp:'yes',resumeFile:null as File|null,resumeName:'' });
  const [sandboxSetup, setSandboxSetup] = useState({ multiTenantIsolation:'',ehrIntegrationFlow:'',aiInferenceScaling:'' });
  const [sandboxAttempts, setSandboxAttempts] = useState(0);
  const [sandboxSuccess, setSandboxSuccess] = useState(false);
  const [sandboxError, setSandboxError] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitSuccess, setSubmitSuccess] = useState(false);

  const technicalSkills: TechSkill[] = [
    { name:'Application Architecture Patterns', level:'Required', color:'text-brand-cyan bg-brand-cyan/10 border-brand-cyan/20' },
    { name:'Cloud Architecture (AWS/GCP)', level:'Required', color:'text-brand-indigo bg-brand-indigo/10 border-brand-indigo/20' },
    { name:'Microservices & Distributed Systems', level:'Required', color:'text-brand-emerald bg-brand-emerald/10 border-brand-emerald/20' },
    { name:'EHR/EMR Interoperability', level:'Required', color:'text-purple-400 bg-purple-400/10 border-purple-400/20' },
    { name:'Database Scaling & RLS', level:'Required', color:'text-amber-400 bg-amber-400/10 border-amber-400/20' },
    { name:'AI Orchestration & Queues', level:'Preferred', color:'text-rose-400 bg-rose-400/10 border-rose-400/20' },
  ];

  const techAreas: TechArea[] = [
    { title:'Healthcare SaaS Applications', desc:'Design multi-tenant microservices layouts isolating database resources via RLS policies.', icon:<Layers className="w-5 h-5" /> },
    { title:'Patient Portal Platforms', desc:'Build responsive, high-performance, and secure applications for client-facing portals.', icon:<Server className="w-5 h-5" /> },
    { title:'Clinical Workflow Applications', desc:'Architect automation pipelines, clinical routing schedulers, and reporting systems.', icon:<Activity className="w-5 h-5" /> },
    { title:'EHR/EMR Integrations', desc:'Build interoperability gateway layouts using HL7 FHIR standards for medical databases.', icon:<Database className="w-5 h-5" /> },
    { title:'AI Healthcare Solutions', desc:'Scale compute-intensive clinical dictation and NLP categorization layers asynchronously.', icon:<Sparkles className="w-5 h-5" /> },
    { title:'Telemedicine Systems', desc:'Design fault-tolerant media channels and signaling layers for real-time video consultations.', icon:<Cpu className="w-5 h-5" /> },
  ];

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => { if (e.target.files?.[0]) { const f=e.target.files[0]; setFormData(p=>({...p,resumeFile:f,resumeName:f.name})); } };
  const handleDragOver = (e: React.DragEvent) => { e.preventDefault(); };
  const handleDrop = (e: React.DragEvent) => { e.preventDefault(); if (e.dataTransfer.files?.[0]) { const f=e.dataTransfer.files[0]; setFormData(p=>({...p,resumeFile:f,resumeName:f.name})); } };

  const validateSandbox = () => {
    setSandboxAttempts(p=>p+1);
    const ok1=sandboxSetup.multiTenantIsolation==='postgresql_rls_tenant';
    const ok2=sandboxSetup.ehrIntegrationFlow==='oauth2_fhir_webhook_dlq';
    const ok3=sandboxSetup.aiInferenceScaling==='decoupled_async_queues';
    if(ok1&&ok2&&ok3){setSandboxSuccess(true);setSandboxError('');}
    else{setSandboxSuccess(false);let n=0;if(!ok1)n++;if(!ok2)n++;if(!ok3)n++;setSandboxError('Application Architecture pre-screen failed. '+n+'/3 designs are non-optimal. Hint: Utilize PostgreSQL Row-Level Security (RLS) for tenant separation; design HL7 FHIR APIs using OAuth 2.0 with event-driven webhook retries/DLQs; and scale compute-heavy AI tasks asynchronously via queues.');}
  };

  const submitApplication = async () => { setIsSubmitting(true); await new Promise(r=>setTimeout(r,2000)); setIsSubmitting(false); setSubmitSuccess(true); };
  const resetForm = () => { setFormStep(1);setSubmitSuccess(false);setSandboxSuccess(false);setSandboxAttempts(0);setSandboxSetup({multiTenantIsolation:'',ehrIntegrationFlow:'',aiInferenceScaling:''});setFormData({name:'',email:'',portfolioUrl:'',primaryLang:'app_architecture',expYears:'8+',cloudExp:'yes',resumeFile:null,resumeName:''}); };

  return (<div className="relative overflow-hidden min-h-screen">
    <div className="fixed top-0 right-1/4 w-[600px] h-[600px] bg-brand-cyan/5 rounded-full blur-[130px] -z-10 pointer-events-none" />
    <div className="fixed bottom-0 left-1/4 w-[500px] h-[500px] bg-brand-indigo/5 rounded-full blur-[130px] -z-10 pointer-events-none" />
    <div className="max-w-6xl mx-auto px-6 py-12 md:py-16">
      <div className="mb-8 flex items-center space-x-2 text-xs"><Link href="/" className="text-gray-500 hover:text-brand-cyan transition-colors">Home</Link><span className="text-gray-600">/</span><Link href="/careers" className="text-gray-500 hover:text-brand-cyan transition-colors">Careers</Link><span className="text-gray-600">/</span><span className="text-white">Application Architect</span></div>
      <header className="mb-12 relative"><div className="absolute -inset-1 bg-gradient-to-r from-brand-cyan/20 to-brand-indigo/20 rounded-3xl blur-2xl opacity-40 -z-10 pointer-events-none" /><div className="glass-panel border border-brand-border rounded-3xl p-8 md:p-12"><div className="grid grid-cols-1 md:grid-cols-12 gap-8 items-center">
        <div className="md:col-span-8 space-y-6">
          <div className="inline-flex items-center space-x-2 bg-gradient-to-r from-brand-cyan/15 to-brand-indigo/15 border border-brand-cyan/20 rounded-full px-4 py-1.5"><div className="w-1.5 h-1.5 bg-brand-cyan rounded-full animate-pulse" /><span className="text-[10px] font-bold text-brand-cyan uppercase tracking-widest">Enterprise Application Design</span><Sparkles className="w-3 h-3 text-brand-cyan" /></div>
          <h1 className="font-display font-extrabold text-3xl sm:text-4xl lg:text-5xl text-white leading-tight">Application Architect Careers at Med Clinic X</h1>
          <p className="text-sm md:text-base text-gray-300 max-w-2xl leading-relaxed">Design, define, and guide the architecture of healthcare software applications and digital platforms.</p>
          <div className="flex flex-wrap gap-3">
            <span className="inline-flex items-center space-x-1.5 text-xs font-semibold px-3 py-1 bg-white/5 border border-brand-border rounded-lg text-white"><Code className="w-3.5 h-3.5 text-brand-cyan" /><span>Architecture</span></span>
            <span className="inline-flex items-center space-x-1.5 text-xs font-semibold px-3 py-1 bg-white/5 border border-brand-border rounded-lg text-white"><Globe className="w-3.5 h-3.5 text-brand-indigo" /><span>Remote (US Only)</span></span>
            
          </div>
        </div>
        <div className="md:col-span-4 flex justify-start md:justify-end"><button onClick={()=>{setActiveTab('apply');const el=document.getElementById('job-content');if(el)el.scrollIntoView({behavior:'smooth'});}} className="w-full md:w-auto inline-flex items-center justify-center space-x-2 bg-gradient-to-r from-brand-cyan to-brand-indigo text-white font-bold px-8 py-4 rounded-2xl hover:opacity-95 transition-opacity shadow-lg shadow-brand-indigo/10 text-sm cursor-pointer"><span>Apply for this Role</span><ArrowRight className="w-4 h-4" /></button></div>
      </div></div></header>
      <div className="border-b border-brand-border mb-8 flex space-x-8">
        <button onClick={()=>setActiveTab('description')} className={`pb-4 text-sm font-bold border-b-2 transition-all cursor-pointer ${activeTab==='description'?'border-brand-cyan text-brand-cyan':'border-transparent text-gray-400 hover:text-white'}`}>Job Description</button>
        <button onClick={()=>setActiveTab('apply')} className={`pb-4 text-sm font-bold border-b-2 transition-all cursor-pointer ${activeTab==='apply'?'border-brand-cyan text-brand-cyan':'border-transparent text-gray-400 hover:text-white'}`}>Apply Portal</button>
      </div>
      <div id="job-content" className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start"><AnimatePresence mode="wait">
        {activeTab==='description' ? (
          <motion.div key="description" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-15}} transition={{duration:0.3}} className="lg:col-span-8 space-y-10">
            <section className="space-y-4"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">About Med Clinic X</h2><p className="text-sm text-gray-300 leading-relaxed">Med Clinic X is a healthcare technology company building secure, scalable, and innovative digital health applications for healthcare organizations across the United States.</p><p className="text-sm text-gray-300 leading-relaxed">We develop healthcare SaaS platforms, AI-driven healthcare systems, patient portals, telemedicine solutions, automation workflows, and enterprise healthcare applications that help clinics, hospitals, and medical organizations improve care delivery and operations.</p><p className="text-sm text-gray-300 leading-relaxed">Our mission is to design powerful healthcare applications that are reliable, scalable, and built for the future of digital health.</p></section>
            <section className="space-y-4"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">Job Overview</h2><p className="text-sm text-gray-300 leading-relaxed">We are seeking an <strong>Application Architect</strong> to design, define, and guide the architecture of healthcare software applications and digital platforms.</p><p className="text-sm text-gray-300 leading-relaxed">In this role, you will create scalable application architectures, establish technical standards, and work closely with engineering teams to build high-performance healthcare solutions. You will play a key role in designing applications that support patient engagement, healthcare workflows, integrations, and AI-powered healthcare experiences.</p></section>
            <section className="space-y-6"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">Responsibilities</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="glass-panel border border-brand-border p-5 rounded-2xl space-y-2"><div className="w-7 h-7 bg-brand-cyan/10 border border-brand-cyan/20 rounded-lg flex items-center justify-center text-brand-cyan mb-2"><Layers className="w-4 h-4" /></div><h3 className="font-semibold text-white text-sm">Application Architecture Design</h3><ul className="text-xs text-gray-400 space-y-1.5 list-disc list-inside"><li>Design scalable and maintainable software architectures.</li><li>Define application frameworks, patterns, and technical standards.</li><li>Create architecture blueprints and technical specs.</li><li>Evaluate technologies and recommend design improvements.</li></ul></div>
              <div className="glass-panel border border-brand-border p-5 rounded-2xl space-y-2"><div className="w-7 h-7 bg-brand-indigo/10 border border-brand-indigo/20 rounded-lg flex items-center justify-center text-brand-indigo mb-2"><Database className="w-4 h-4" /></div><h3 className="font-semibold text-white text-sm">Healthcare Application Development</h3><ul className="text-xs text-gray-400 space-y-1.5 list-disc list-inside"><li>Architect healthcare SaaS applications and digital platforms.</li><li>Design solutions for patient portals and clinical workflows.</li><li>Support secure EHR/EMR integration architectures.</li><li>Ensure applications meet scalability and security controls.</li></ul></div>
              <div className="glass-panel border border-brand-border p-5 rounded-2xl space-y-2"><div className="w-7 h-7 bg-brand-emerald/10 border border-brand-emerald/20 rounded-lg flex items-center justify-center text-brand-emerald mb-2"><Shield className="w-4 h-4" /></div><h3 className="font-semibold text-white text-sm">Cloud & System Design</h3><ul className="text-xs text-gray-400 space-y-1.5 list-disc list-inside"><li>Design cloud-native application solutions.</li><li>Support containerized application deployments.</li><li>Define security, reliability, and auto-scaling strategies.</li><li>Collaborate with DevOps teams on application delivery pipelines.</li></ul></div>
              <div className="glass-panel border border-brand-border p-5 rounded-2xl space-y-2"><div className="w-7 h-7 bg-purple-500/10 border border-purple-500/20 rounded-lg flex items-center justify-center text-purple-400 mb-2"><Code className="w-4 h-4" /></div><h3 className="font-semibold text-white text-sm">Engineering Collaboration</h3><ul className="text-xs text-gray-400 space-y-1.5 list-disc list-inside"><li>Guide software engineering leads on architecture decisions.</li><li>Review code structures, patterns, and database schemas.</li><li>Solve complex technical bottlenecks.</li><li>Promote coding best practices and design standards.</li></ul></div>
            </div></section>
            <section className="space-y-4"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">Qualifications</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-8"><div className="space-y-3"><h3 className="font-semibold text-white text-xs uppercase tracking-wider text-brand-cyan">Required</h3><ul className="text-xs text-gray-400 space-y-2 list-disc list-inside"><li>Bachelor’s degree in CS, Software Engineering, or related field.</li><li>Strong experience in application architecture and software design.</li><li>Experience designing enterprise-level SaaS applications.</li><li>Strong understanding of software development lifecycle and APIs.</li><li>Excellent technical communication and system design documentation skills.</li></ul></div><div className="space-y-3"><h3 className="font-semibold text-white text-xs uppercase tracking-wider text-brand-indigo">Preferred</h3><ul className="text-xs text-gray-400 space-y-2 list-disc list-inside"><li>Experience in US healthcare or healthcare SaaS environments.</li><li>Familiarity with HIPAA compliance and healthcare app security.</li><li>Experience with EHR/EMR integration systems (Epic, Cerner).</li><li>Knowledge of AI healthcare application architectures.</li><li>Background in enterprise software development and cloud patterns.</li></ul></div></div></section>
            <section className="space-y-4"><h2 className="font-display font-extrabold text-xl sm:text-2xl text-white">Why Join Med Clinic X?</h2><p className="text-sm text-gray-300 leading-relaxed">At Med Clinic X, you will architect the applications that support the next generation of healthcare technology. You will:</p><ul className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs text-gray-400">{['Design healthcare applications used by US organizations','Influence software architecture decisions','Work with engineering and product teams','Build scalable digital health platforms','Contribute to healthcare technology innovation'].map((item,i)=>(<li key={i} className="flex items-start space-x-2"><CheckCircle className="w-4 h-4 text-brand-emerald shrink-0 mt-0.5" /><span>{item}</span></li>))}</ul></section>
          </motion.div>
        ) : (
          <motion.div key="apply" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-15}} transition={{duration:0.3}} className="lg:col-span-8">
            <div className="glass-panel border border-brand-border rounded-3xl p-6 md:p-8">
              <div className="flex items-center justify-between mb-8 border-b border-brand-border pb-4 font-mono text-[10px]"><div className="flex space-x-4"><span className={formStep===1?'text-brand-cyan font-bold':'text-gray-500'}>01. Profile</span><span className={formStep===2?'text-brand-cyan font-bold':'text-gray-500'}>02. Experience</span><span className={formStep===3?'text-brand-cyan font-bold':'text-gray-500'}>03. Architect Sandbox</span><span className={formStep===4?'text-brand-cyan font-bold':'text-gray-500'}>04. Submit</span></div><span className="text-gray-500">Step {formStep} of 4</span></div>
              {submitSuccess ? (<motion.div initial={{opacity:0,scale:0.95}} animate={{opacity:1,scale:1}} className="text-center py-12 space-y-6">
                <div className="w-16 h-16 bg-brand-emerald/10 border border-brand-emerald/20 text-brand-emerald rounded-full flex items-center justify-center mx-auto"><CheckCircle className="w-8 h-8" /></div>
                <div className="space-y-2"><h3 className="font-display font-extrabold text-2xl text-white">Application Architect Pre-screen Completed!</h3><p className="text-sm text-gray-400 max-w-md mx-auto leading-relaxed">Your application design score is logged. We verified your Row-Level Security (RLS) data isolation, FHIR API oauth flow, and decoupled queue-based AI scaling architecture choices.</p></div>
                <button onClick={resetForm} className="inline-flex items-center space-x-2 text-xs font-bold text-brand-cyan hover:underline cursor-pointer"><span>Reset and restart mock screening</span><ArrowRight className="w-3.5 h-3.5" /></button>
              </motion.div>) : (<>
                {formStep===1 && (<div className="space-y-5"><h3 className="font-display font-extrabold text-lg text-white">Let&apos;s start with your basics</h3><div className="space-y-4"><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Full Name <span className="text-red-400">*</span></label><input type="text" required value={formData.name} onChange={(e)=>setFormData(p=>({...p,name:e.target.value}))} placeholder="Drew Harris" className="w-full bg-brand-bg/50 border border-brand-border rounded-xl px-4 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-brand-cyan transition-colors" /></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Email Address <span className="text-red-400">*</span></label><input type="email" required value={formData.email} onChange={(e)=>setFormData(p=>({...p,email:e.target.value}))} placeholder="drew.architect@example.com" className="w-full bg-brand-bg/50 border border-brand-border rounded-xl px-4 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-brand-cyan transition-colors" /></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">GitHub or Portfolio URL</label><input type="url" value={formData.portfolioUrl} onChange={(e)=>setFormData(p=>({...p,portfolioUrl:e.target.value}))} placeholder="https://github.com/drewharris-arch" className="w-full bg-brand-bg/50 border border-brand-border rounded-xl px-4 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-brand-cyan transition-colors" /></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Upload Resume / CV <span className="text-red-400">*</span></label><div onDragOver={handleDragOver} onDrop={handleDrop} className="border-2 border-dashed border-brand-border hover:border-brand-cyan/50 rounded-2xl p-6 text-center bg-white/2 cursor-pointer transition-colors relative"><input type="file" accept=".pdf,.doc,.docx" onChange={handleFileUpload} className="absolute inset-0 opacity-0 cursor-pointer w-full h-full" /><Upload className="w-8 h-8 text-gray-500 mx-auto mb-2" />{formData.resumeName?<p className="text-sm font-semibold text-brand-cyan">{formData.resumeName}</p>:<><p className="text-xs text-gray-300 font-semibold mb-1">Drag and drop your file here, or click to browse</p><p className="text-[10px] text-gray-500">Supports PDF, DOCX, DOC up to 10MB</p></>}</div></div></div><div className="pt-4 flex justify-end"><button type="button" disabled={!formData.name||!formData.email||!formData.resumeName} onClick={()=>setFormStep(2)} className="inline-flex items-center space-x-2 bg-brand-cyan text-brand-bg font-bold px-5 py-3 rounded-xl hover:opacity-90 transition-opacity text-xs disabled:opacity-30 cursor-pointer"><span>Next Step</span><ArrowRight className="w-3.5 h-3.5" /></button></div></div>)}
                {formStep===2 && (<div className="space-y-5"><h3 className="font-display font-extrabold text-lg text-white">Architecture Profile</h3><div className="space-y-4"><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Primary Architecture Focus</label><select value={formData.primaryLang} onChange={(e)=>setFormData(p=>({...p,primaryLang:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-brand-cyan transition-colors"><option value="app_architecture">Application & Enterprise Software Architecture</option><option value="microservices_cloud">Microservices & Cloud-Native (AWS/GCP)</option><option value="relational_nosql">Distributed Database & Caching Topology</option><option value="hybrid_enterprise">Monolithic Decompositions & API Gateways</option></select></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Years of Software Architecture Experience</label><select value={formData.expYears} onChange={(e)=>setFormData(p=>({...p,expYears:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-brand-cyan transition-colors"><option value="3-5">3 to 5 Years</option><option value="5-8">5 to 8 Years</option><option value="8+">8+ Years (Recommended)</option></select></div><div><label className="block text-xs font-semibold text-gray-300 mb-1.5">Do you have experience designing HIPAA-compliant SaaS platforms?</label><div className="flex gap-4">{['yes','no'].map(val=>(<button key={val} type="button" onClick={()=>setFormData(p=>({...p,cloudExp:val}))} className={`flex-1 border text-sm font-semibold py-2.5 rounded-xl capitalize transition-all cursor-pointer ${formData.cloudExp===val?'bg-brand-indigo/15 border-brand-indigo text-white':'border-brand-border text-gray-400 hover:border-gray-500'}`}>{val}</button>))}</div></div></div><div className="pt-4 flex justify-between"><button type="button" onClick={()=>setFormStep(1)} className="inline-flex items-center border border-brand-border text-gray-300 hover:text-white font-semibold px-5 py-3 rounded-xl transition-colors text-xs cursor-pointer">Back</button><button type="button" onClick={()=>setFormStep(3)} className="inline-flex items-center space-x-2 bg-brand-cyan text-brand-bg font-bold px-5 py-3 rounded-xl hover:opacity-90 transition-opacity text-xs cursor-pointer"><span>Proceed to Sandbox</span><ArrowRight className="w-3.5 h-3.5" /></button></div></div>)}
                {formStep===3 && (<div className="space-y-5"><div className="flex justify-between items-start"><div><h3 className="font-display font-extrabold text-lg text-white">Application Solutions Architecture Sandbox</h3><p className="text-xs text-gray-400 mt-1">Design multi-tenant data structures, establish secure EHR integration APIs, and scale AI workloads.</p></div><span className="text-[9px] font-bold px-2 py-0.5 bg-brand-cyan/15 text-brand-cyan border border-brand-cyan/20 rounded font-mono">SAAS / APP</span></div>
                  <div className="space-y-4 font-sans text-xs">
                    <div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-3"><div className="font-mono text-white text-xs font-semibold flex items-center space-x-2"><span className="w-2 h-2 bg-brand-cyan rounded-full shrink-0" /><span>Scenario 1: Multi-Tenant Data Separation</span></div><p className="text-gray-400 italic text-[11px] leading-relaxed">&quot;How do you architect data isolation for a multi-tenant healthcare SaaS application containing sensitive patient health records?&quot;</p><select value={sandboxSetup.multiTenantIsolation} onChange={(e)=>setSandboxSetup(p=>({...p,multiTenantIsolation:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-lg px-3 py-2 text-xs text-white focus:outline-none focus:border-brand-cyan"><option value="">-- Select Data Isolation Strategy --</option><option value="postgresql_rls_tenant">Configure PostgreSQL Row-Level Security (RLS) policies on a shared database to dynamically enforce tenant scopes per active connection (Correct!)</option><option value="flat_single_tenant_id">Store all records in a single database with a tenant_id column, checking queries in frontend javascript loops only</option><option value="manual_vm_db_setup">Deploy a separate, isolated virtual machine and physical database server manually for each client clinic</option></select></div>
                    <div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-3"><div className="font-mono text-white text-xs font-semibold flex items-center space-x-2"><span className="w-2 h-2 bg-brand-indigo rounded-full shrink-0" /><span>Scenario 2: Real-time EHR Integration API Gateway</span></div><p className="text-gray-400 italic text-[11px] leading-relaxed">&quot;Our patient portal must synchronize updates in real-time with multiple external hospital EHR systems. How do you design this application integration layer?&quot;</p><select value={sandboxSetup.ehrIntegrationFlow} onChange={(e)=>setSandboxSetup(p=>({...p,ehrIntegrationFlow:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-lg px-3 py-2 text-xs text-white focus:outline-none focus:border-brand-cyan"><option value="">-- Select Integration Strategy --</option><option value="oauth2_fhir_webhook_dlq">Build a secure FHIR API gateway layer using OAuth 2.0 with scopes, coupled with an event-driven webhook retry queue and Dead Letter Queue (DLQ) (Correct!)</option><option value="poll_external_databases">Establish direct database connections to each external hospital EHR and run select queries every 5 seconds</option><option value="sftp_xml_drops">Configure batch SFTP XML file drops from EHR systems to import clinical records once every 24 hours</option></select></div>
                    <div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-3"><div className="font-mono text-white text-xs font-semibold flex items-center space-x-2"><span className="w-2 h-2 bg-brand-emerald rounded-full shrink-0" /><span>Scenario 3: Asynchronous AI Workload Scaling</span></div><p className="text-gray-400 italic text-[11px] leading-relaxed">&quot;We are deploying AI-driven medical dictation features within our patient portals. How do you architect this high-load inference service?&quot;</p><select value={sandboxSetup.aiInferenceScaling} onChange={(e)=>setSandboxSetup(p=>({...p,aiInferenceScaling:e.target.value}))} className="w-full bg-brand-bg border border-brand-border rounded-lg px-3 py-2 text-xs text-white focus:outline-none focus:border-brand-cyan"><option value="">-- Select Scaling Strategy --</option><option value="decoupled_async_queues">Deploy the AI model as an isolated, auto-scaled container service utilizing asynchronous message queues (RabbitMQ/SQS) to decouple API requests from model processing (Correct!)</option><option value="synchronous_inline_nextjs">Run the AI inference computations synchronously inline inside the Next.js API route thread to simplify deployments</option><option value="monolith_large_server">Route all AI speech requests directly to a single large monolithic CPU database server to execute jobs in order</option></select></div>
                  </div>
                  {sandboxError&&<div className="flex items-start space-x-2.5 p-3.5 bg-red-950/40 border border-red-500/20 text-red-300 rounded-xl text-xs"><AlertCircle className="w-4 h-4 shrink-0 mt-0.5" /><span>{sandboxError}</span></div>}
                  {sandboxSuccess&&<div className="flex items-start space-x-2.5 p-3.5 bg-brand-emerald/10 border border-brand-emerald/20 text-brand-emerald rounded-xl text-xs"><CheckCircle className="w-4 h-4 shrink-0 mt-0.5" /><span>Application Architecture pre-screen approved! Row-level security settings verified, secure FHIR integrations checked, and queue-based AI scaling patterns confirmed.</span></div>}
                  <div className="pt-4 flex justify-between"><button type="button" onClick={()=>setFormStep(2)} className="inline-flex items-center border border-brand-border text-gray-300 hover:text-white font-semibold px-5 py-3 rounded-xl transition-colors text-xs cursor-pointer">Back</button>{!sandboxSuccess?(<button type="button" onClick={validateSandbox} className="inline-flex items-center space-x-2 bg-brand-cyan text-brand-bg font-bold px-5 py-3 rounded-xl hover:opacity-90 transition-opacity text-xs cursor-pointer"><span>Submit Solutions Assessment ({sandboxAttempts} attempts)</span></button>):(<button type="button" onClick={()=>setFormStep(4)} className="inline-flex items-center space-x-2 bg-gradient-to-r from-brand-cyan to-brand-indigo text-white font-bold px-5 py-3 rounded-xl hover:opacity-95 transition-opacity text-xs cursor-pointer"><span>Proceed to Review</span><ArrowRight className="w-3.5 h-3.5" /></button>)}</div></div>)}
                {formStep===4 && (<div className="space-y-5"><h3 className="font-display font-extrabold text-lg text-white">Review & Submit Application</h3><div className="space-y-4 text-xs font-mono"><div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-2"><p className="text-gray-500 uppercase text-[10px] tracking-wider mb-2 font-bold font-sans">Personal Profile</p><p className="text-gray-300"><span className="text-gray-500 font-sans">Name:</span> {formData.name}</p><p className="text-gray-300"><span className="text-gray-500 font-sans">Email:</span> {formData.email}</p>{formData.portfolioUrl&&<p className="text-gray-300"><span className="text-gray-500 font-sans">Portfolio:</span> {formData.portfolioUrl}</p>}<p className="text-gray-300"><span className="text-gray-500 font-sans">Resume:</span> {formData.resumeName}</p></div><div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-2"><p className="text-gray-500 uppercase text-[10px] tracking-wider mb-2 font-bold font-sans">Technical Profile</p><p className="text-gray-300"><span className="text-gray-500 font-sans">Primary Focus:</span> <span className="capitalize">{formData.primaryLang.replace('_',' ')}</span></p><p className="text-gray-300"><span className="text-gray-500 font-sans">Experience:</span> {formData.expYears} years</p><p className="text-gray-300"><span className="text-gray-500 font-sans">SaaS Architecture Exp:</span> {formData.cloudExp}</p></div><div className="bg-white/2 border border-white/5 p-4 rounded-xl space-y-1.5"><p className="text-gray-500 uppercase text-[10px] tracking-wider mb-2 font-bold font-sans">Solutions Result</p><p className="text-brand-emerald flex items-center space-x-1.5"><CheckCircle className="w-3.5 h-3.5" /><span>PostgreSQL RLS logical boundaries, FHIR API endpoints, and asynchronous queue layouts validated</span></p></div></div><div className="pt-4 flex justify-between"><button type="button" onClick={()=>setFormStep(3)} className="inline-flex items-center border border-brand-border text-gray-300 hover:text-white font-semibold px-5 py-3 rounded-xl transition-colors text-xs cursor-pointer">Back</button><button type="button" disabled={isSubmitting} onClick={submitApplication} className="inline-flex items-center space-x-2 bg-gradient-to-r from-brand-cyan to-brand-indigo text-white font-bold px-6 py-3 rounded-xl hover:opacity-95 transition-opacity text-xs disabled:opacity-50 cursor-pointer">{isSubmitting?<><div className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" /><span>Submitting application...</span></>:<><Send className="w-3.5 h-3.5" /><span>Submit Application</span></>}</button></div></div>)}
              </>)}
            </div></motion.div>)}
        </AnimatePresence>
        <aside className="lg:col-span-4 space-y-6">
          <div className="glass-panel border border-brand-border rounded-3xl p-6 space-y-6"><h3 className="font-display font-extrabold text-base text-white">Technical Core</h3><div className="flex flex-wrap gap-2">{technicalSkills.map((skill,i)=>(<span key={i} className={`text-[10px] font-semibold px-2.5 py-1 rounded-md border tracking-wide uppercase ${skill.color}`}>{skill.name}</span>))}</div></div>
          <div className="glass-panel border border-brand-border rounded-3xl p-6 space-y-6"><div className="flex items-center space-x-2 text-white"><Shield className="w-4 h-4 text-brand-cyan" /><h3 className="font-display font-extrabold text-base">Systems You Will Work With</h3></div><div className="space-y-4">{techAreas.map((area,i)=>(<div key={i} className="flex space-x-3.5"><div className="w-8 h-8 rounded-xl bg-white/2 border border-white/5 flex items-center justify-center text-brand-cyan shrink-0 mt-0.5">{area.icon}</div><div><h4 className="text-xs font-semibold text-white">{area.title}</h4><p className="text-[11px] text-gray-400 leading-relaxed mt-0.5">{area.desc}</p></div></div>))}</div></div>
        </aside>
      </div>
    </div>
  </div>);
}
